# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Scattered path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 32

In [13]:
raw_data = pd.concat([sensors_data.iloc[:,:32], position_data], axis=1)
raw_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32,Pos X,Pos Y,Pos Z
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,119.192223,71.226714,118.686237,112.286222,140.101016,108.047877,140.244547,-45.581275,30.239368,-60.00
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,130.105863,86.975311,115.767851,121.663582,139.407084,112.790714,128.411134,-45.188830,30.181623,-59.96
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,125.534465,72.718397,114.162279,111.606383,147.146669,106.249265,130.156309,-44.791865,30.131806,-59.92
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,123.938584,80.966785,119.041195,116.155669,142.364016,103.720363,132.493487,-44.390422,30.089935,-59.88
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,125.710523,77.971384,114.921061,117.115181,132.798389,105.749524,128.893260,-43.984540,30.056029,-59.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,100.314203,98.244115,69.740835,140.564141,130.326611,123.473334,110.321790,-59.939858,51.788725,37.52
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,98.280164,108.820189,65.601420,149.970280,131.412166,132.120534,110.618646,-59.963718,51.389997,37.56
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,89.854083,106.636687,75.778925,143.749740,129.105638,135.492966,109.283794,-59.981583,50.990713,37.60
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,100.182792,98.237232,74.725177,142.330470,131.765898,132.120728,100.956413,-59.993448,50.591032,37.64
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,95.817155,100.139610,74.908658,150.114924,123.632458,129.010136,106.652696,-59.999315,50.191116,37.68

# PowerTransformer

In [14]:
from sklearn.preprocessing import PowerTransformer

In [15]:
scaler = PowerTransformer()
sensors_data = scaler.fit_transform(sensors_data)

# Split the data into training and testing sets

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [17]:
X_train

array([[ 0.53966184,  1.33303809,  0.71990234, ...,  0.58504781,
        -1.8204507 ,  0.55381811],
       [-1.01434196,  0.82923268, -1.23757134, ...,  0.86427218,
        -0.75836698,  1.11030919],
       [ 1.4564306 ,  1.30991094,  1.15458945, ...,  0.35736533,
         0.2754791 , -1.44567167],
       ...,
       [-0.97635099, -0.46221765, -1.19899931, ...,  1.33298197,
         0.51455256, -0.30015568],
       [-0.79641268, -0.54592762,  0.17829529, ..., -0.50679628,
         0.83165029,  0.73380819],
       [ 1.03883734,  0.90731307,  0.88700831, ..., -0.42549299,
        -0.92324772, -0.30327459]])

In [18]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [20]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [21]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9827693070893422
Mean Squared Error: 7.58810133748221
Root Mean Squared Error: 2.7539002950929414
R2 Score: 0.9827693070893422
Mean Absolute Error: 2.2167861861721962
Median Absolute Error: 1.8752385995310685
Explained Variance Score: 0.9827781734751957
Time taken: 0.006953001022338867
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.8207034712012451
Mean Squared Error: 89.83121778903624
Root Mean Squared Error: 9.451351574439494
R2 Score: 0.8207034712012451
Mean Absolute Error: 5.907228885264762
Median Absolute Error: 2.9205260661579993
Explained Variance Score: 0.8211082818799484
Time taken: 0.045198678970336914
====================================================================================================
RandomForestRegressor
Accuracy: 0.9643015439877454
Mean Squared Error: 16.20676026434003
Root Mean Squared Error: 4.022314510529004
R2 Score: 0.9643015439877454
Mean Absolute Error: 3.2530936865064604
Median Absolute Error: 2.786593071366466
Explained Variance Score: 0.9645805595503778
Time taken: 2.586137056350708
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9891446627506991
Mean Squared Error: 5.38146247222697
Root Mean Squared Error: 2.187545894654215
R2 Score: 0.9891446627506991
Mean Absolute Error: 1.4954077010374558
Median Absolute Error: 1.0409388050305004
Explained Variance Score: 0.9891494396120498
Time taken: 0.05612349510192871
====================================================================================================
XGBRegressor
Accuracy: 0.9627114848662895
Mean Squared Error: 18.914684919892363
Root Mean Squared Error: 4.3353968163696655
R2 Score: 0.9627114848662895
Mean Absolute Error: 3.2594148251791553
Median Absolute Error: 2.475136440645387
Explained Variance Score: 0.962740271290409
Time taken: 0.5880510807037354
====================================================================================================

# Cross Validation

In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 7.59
Fold 1 - Mean Absolute Error (MAE): 2.22
Fold 1 - Root Mean Squared Error (RMSE): 2.75
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 7.74
Fold 2 - Mean Absolute Error (MAE): 2.19
Fold 2 - Root Mean Squared Error (RMSE): 2.78
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 7.87
Fold 3 - Mean Absolute Error (MAE): 2.23
Fold 3 - Root Mean Squared Error (RMSE): 2.81
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 7.87
Fold 4 - Mean Absolute Error (MAE): 2.23
Fold 4 - Root Mean Squared Error (RMSE): 2.81
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 7.96
Fold 5 - Mean Absolute Error (MAE): 2.23
Fold 5 - Root Mean Squared Error (RMSE): 2.82
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 7.81
Mean MAE: 2.22
Mean RMSE: 2.79
Mean time: 0.01 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 87.14
Fold 1 - Mean Absolute Error (MAE): 5.80
Fold 1 - Root Mean Squared Error (RMSE): 9.34
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 88.42
Fold 2 - Mean Absolute Error (MAE): 5.83
Fold 2 - Root Mean Squared Error (RMSE): 9.40
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 77.93
Fold 3 - Mean Absolute Error (MAE): 5.56
Fold 3 - Root Mean Squared Error (RMSE): 8.83
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 105.79
Fold 4 - Mean Absolute Error (MAE): 6.60
Fold 4 - Root Mean Squared Error (RMSE): 10.29
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 91.87
Fold 5 - Mean Absolute Error (MAE): 6.05
Fold 5 - Root Mean Squared Error (RMSE): 9.58
Fold 5 - Time taken: 0.05 seconds
Mean MSE: 90.23
Mean MAE: 5.97
Mean RMSE: 9.49
Mean time: 0.05 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 16.26
Fold 1 - Mean Absolute Error (MAE): 3.25
Fold 1 - Root Mean Squared Error (RMSE): 4.03
Fold 1 - Time taken: 3.84 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 15.58
Fold 2 - Mean Absolute Error (MAE): 3.20
Fold 2 - Root Mean Squared Error (RMSE): 3.95
Fold 2 - Time taken: 4.63 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 16.74
Fold 3 - Mean Absolute Error (MAE): 3.33
Fold 3 - Root Mean Squared Error (RMSE): 4.09
Fold 3 - Time taken: 5.83 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 17.00
Fold 4 - Mean Absolute Error (MAE): 3.34
Fold 4 - Root Mean Squared Error (RMSE): 4.12
Fold 4 - Time taken: 4.43 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 15.76
Fold 5 - Mean Absolute Error (MAE): 3.20
Fold 5 - Root Mean Squared Error (RMSE): 3.97
Fold 5 - Time taken: 4.37 seconds
Mean MSE: 16.27
Mean MAE: 3.26
Mean RMSE: 4.03
Mean time: 4.62 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.38
Fold 1 - Mean Absolute Error (MAE): 1.50
Fold 1 - Root Mean Squared Error (RMSE): 2.32
Fold 1 - Time taken: 0.10 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.30
Fold 2 - Mean Absolute Error (MAE): 1.52
Fold 2 - Root Mean Squared Error (RMSE): 2.30
Fold 2 - Time taken: 0.12 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.66
Fold 3 - Mean Absolute Error (MAE): 1.58
Fold 3 - Root Mean Squared Error (RMSE): 2.38
Fold 3 - Time taken: 0.12 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 5.83
Fold 4 - Mean Absolute Error (MAE): 1.60
Fold 4 - Root Mean Squared Error (RMSE): 2.42
Fold 4 - Time taken: 0.11 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 5.93
Fold 5 - Mean Absolute Error (MAE): 1.58
Fold 5 - Root Mean Squared Error (RMSE): 2.44
Fold 5 - Time taken: 0.12 seconds
Mean MSE: 5.62
Mean MAE: 1.56
Mean RMSE: 2.37
Mean time: 0.11 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 18.91
Fold 1 - Mean Absolute Error (MAE): 3.26
Fold 1 - Root Mean Squared Error (RMSE): 4.35
Fold 1 - Time taken: 13.88 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 19.09
Fold 2 - Mean Absolute Error (MAE): 3.23
Fold 2 - Root Mean Squared Error (RMSE): 4.37
Fold 2 - Time taken: 15.18 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 20.79
Fold 3 - Mean Absolute Error (MAE): 3.35
Fold 3 - Root Mean Squared Error (RMSE): 4.56
Fold 3 - Time taken: 12.90 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 19.92
Fold 4 - Mean Absolute Error (MAE): 3.31
Fold 4 - Root Mean Squared Error (RMSE): 4.46
Fold 4 - Time taken: 12.56 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 21.05
Fold 5 - Mean Absolute Error (MAE): 3.31
Fold 5 - Root Mean Squared Error (RMSE): 4.59
Fold 5 - Time taken: 11.14 seconds
Mean MSE: 19.95
Mean MAE: 3.29
Mean RMSE: 4.47
Mean time: 13.13 seconds
--------------------------------------------------