# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Smoothed path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Concatenating Dataframes

In [13]:
raw_data = pd.concat([sensors_data, position_data], axis = 1)
raw_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48,Pos X,Pos Y,Pos Z
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967,-45.581275,30.239368,-60.00
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967,-45.188830,30.181623,-59.96
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967,-44.791865,30.131806,-59.92
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967,-44.390422,30.089935,-59.88
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967,-43.984540,30.056029,-59.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096,-59.939858,51.788725,37.52
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096,-59.963718,51.389997,37.56
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096,-59.981583,50.990713,37.60
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096,-59.993448,50.591032,37.64
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096,-59.999315,50.191116,37.68