# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Scattered path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 40

In [13]:
raw_data = pd.concat([sensors_data.iloc[:,:40], position_data], axis=1)
raw_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor34,sensor35,sensor36,sensor37,sensor38,sensor39,sensor40,Pos X,Pos Y,Pos Z
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.070545,82.893900,98.589125,127.512697,129.486254,109.733925,122.659778,-45.581275,30.239368,-60.00
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,111.452682,73.125233,101.282473,125.960497,134.441514,113.915353,123.190051,-45.188830,30.181623,-59.96
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,118.956893,79.333567,97.267900,133.077599,139.007648,112.052375,117.562515,-44.791865,30.131806,-59.92
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,116.580605,87.824924,94.036434,126.398457,132.107357,108.861984,129.042510,-44.390422,30.089935,-59.88
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,115.118536,81.096908,93.196633,123.182719,128.847588,108.706859,119.970422,-43.984540,30.056029,-59.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,107.981938,85.180655,73.015884,147.381832,135.026131,119.309378,112.129281,-59.939858,51.788725,37.52
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,106.740114,85.424751,68.648789,136.726601,132.596080,119.776043,109.341785,-59.963718,51.389997,37.56
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,102.425103,86.943908,73.622470,141.008696,136.607714,124.257271,108.008908,-59.981583,50.990713,37.60
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,110.783778,81.725527,68.838207,140.712648,140.075617,125.544587,114.946916,-59.993448,50.591032,37.64
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,103.197607,83.834217,69.625782,150.800243,131.837953,120.001152,109.766753,-59.999315,50.191116,37.68

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
233,136.310276,150.384808,115.241974,137.637955,117.291541,146.146202,78.341112,97.943548,134.871243,152.990180,...,63.914573,87.619839,124.152237,144.832337,88.736673,121.186405,108.173911,130.995238,65.964310,105.349250
433,117.216199,143.936832,85.941792,113.718086,129.516070,143.437491,89.314080,120.160527,119.588970,133.328797,...,96.977724,94.758331,115.035795,137.374467,69.654533,99.454581,127.165148,133.664254,80.935308,112.044007
1430,146.817294,150.086441,121.703266,124.232207,123.061674,124.593387,81.544715,90.485171,139.849309,134.497568,...,77.396928,76.561616,135.041172,127.084607,93.700129,103.835466,120.820151,128.786508,94.515361,80.176141
307,125.850460,140.721249,119.845559,134.493230,102.363626,129.254969,79.529738,117.701210,134.691676,143.238576,...,72.204929,90.847143,114.974615,130.542340,95.172722,122.963722,98.014574,126.879814,78.669088,109.928746
2197,139.014239,128.180114,132.661534,120.944083,119.856020,100.881685,109.353318,87.625060,142.014413,125.605938,...,86.506994,73.733019,130.082710,114.724938,122.117498,93.762063,112.250302,99.193848,96.431511,84.568286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,130.751581,128.682978,105.120199,100.689118,129.783160,129.376056,105.830734,109.113527,132.046751,121.223918,...,91.460819,78.253837,122.091667,111.124861,103.913664,99.922609,122.707208,126.397366,99.969125,88.134085
1095,123.885788,139.526533,84.737342,96.710272,137.029086,149.761441,114.098792,116.684965,123.098980,131.044254,...,102.542809,111.914253,117.520099,127.223376,75.560846,92.103865,121.316796,133.848540,97.383919,102.297738
1130,117.705787,127.908987,86.522797,106.445743,143.134803,148.555034,113.875577,122.116334,115.590718,122.626193,...,107.494969,107.256587,128.427037,129.324954,77.388964,100.409632,134.609795,138.051854,97.544267,94.832262
1294,120.007510,126.895272,107.170011,102.032684,125.874924,127.836227,116.742468,115.698891,108.807729,107.730241,...,112.265567,99.373877,107.203389,119.762184,87.913304,95.052745,114.163863,120.113389,101.505071,107.527440
860,142.091967,144.929032,117.727627,131.181538,121.255144,126.722988,87.921926,93.251797,140.945402,155.922155,...,73.086046,71.315165,121.956253,134.890009,91.081224,116.285614,107.783692,120.950343,78.687291,94.793262

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9826722510290341
Mean Squared Error: 7.601597710031046
Root Mean Squared Error: 2.756250491686739
R2 Score: 0.9826722510290341
Mean Absolute Error: 2.2229147549975
Median Absolute Error: 1.896254514252382
Explained Variance Score: 0.9826819429203993
Time taken: 0.006952762603759766
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.8185718858978959
Mean Squared Error: 91.10855829637494
Root Mean Squared Error: 9.516470249731858
R2 Score: 0.8185718858978959
Mean Absolute Error: 5.9514984873061225
Median Absolute Error: 3.071650831678433
Explained Variance Score: 0.8188149825939038
Time taken: 0.05165362358093262
====================================================================================================
RandomForestRegressor
Accuracy: 0.9619754892163491
Mean Squared Error: 17.028280762971345
Root Mean Squared Error: 4.122896676988277
R2 Score: 0.9619754892163491
Mean Absolute Error: 3.2933056281032926
Median Absolute Error: 2.832551900958473
Explained Variance Score: 0.9622316322755505
Time taken: 2.745076894760132
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9893778266416257
Mean Squared Error: 5.208620743874882
Root Mean Squared Error: 2.167830928081484
R2 Score: 0.9893778266416257
Mean Absolute Error: 1.4728229349697317
Median Absolute Error: 1.0211162976778294
Explained Variance Score: 0.9893997435269132
Time taken: 0.05264639854431152
====================================================================================================
XGBRegressor
Accuracy: 0.9627114848662895
Mean Squared Error: 18.914684919892363
Root Mean Squared Error: 4.3353968163696655
R2 Score: 0.9627114848662895
Mean Absolute Error: 3.2594148251791553
Median Absolute Error: 2.475136440645387
Explained Variance Score: 0.962740271290409
Time taken: 0.5145461559295654
====================================================================================================