# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_smoothed_48_reg_frontback_random.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
1,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
2,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
3,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
4,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2439,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2440,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2441,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2442,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
1,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
2,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
3,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
4,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978,103.621456,116.367383,...,101.700814,100.337456,104.509481,86.771038,126.929330,113.151074,100.412663,130.746911,81.214730,116.870960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2439,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2440,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2441,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608
2442,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368,117.581730,109.290162,...,108.283410,120.752985,110.881606,70.091429,136.199254,112.890068,133.533911,116.368483,107.442876,82.420608

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 8

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:8]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
0,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978
1,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978
2,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978
3,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978
4,103.109949,133.205651,83.042591,120.306119,123.931862,148.486919,110.881819,137.286978
...,...,...,...,...,...,...,...,...
2438,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368
2439,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368
2440,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368
2441,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368
2442,130.673666,111.836664,105.548784,75.975172,151.591931,139.547208,132.537526,119.364368

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
233,137.088251,154.908326,114.163481,136.686830,110.143254,133.844984,74.647337,110.694758
433,121.996240,139.828655,85.376573,110.944375,128.958978,145.501671,98.144219,121.533335
1430,145.806191,146.146408,117.319053,117.430557,127.485820,128.724114,88.829758,91.552246
307,128.247260,148.521654,113.526459,135.116641,103.862118,130.069234,84.243986,113.499170
2197,140.640466,131.614452,131.061428,116.374968,120.928519,109.543848,109.153975,88.887218
...,...,...,...,...,...,...,...,...
1638,130.717499,127.877133,110.495672,108.652616,126.443361,122.981283,102.815350,101.789097
1095,124.330215,134.685655,86.912868,99.643150,139.712080,148.829885,110.146504,119.063011
1130,124.510487,130.962065,84.026910,96.290930,143.794283,149.246145,116.159429,122.034053
1294,115.058644,119.713791,97.896691,104.655166,127.488700,133.673829,114.117775,117.985472
860,139.798264,149.025007,117.890838,129.310959,117.409802,128.728203,79.800268,100.063446

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9953076557595594
Mean Squared Error: 1.9785700123196712
Root Mean Squared Error: 1.40602588471779
R2 Score: 0.9953076557595594
Mean Absolute Error: 1.1403872956923042
Median Absolute Error: 1.022430558338124
Explained Variance Score: 0.9953526469345109
Time taken: 0.003509998321533203
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.9970892427889746
Mean Squared Error: 1.6325093674851576
Root Mean Squared Error: 1.2527753033625422
R2 Score: 0.9970892427889746
Mean Absolute Error: 0.5134850785703509
Median Absolute Error: 0.31899817317943757
Explained Variance Score: 0.9971006010408537
Time taken: 0.00950002670288086
====================================================================================================
RandomForestRegressor
Accuracy: 0.9995663665550998
Mean Squared Error: 0.22374532990678034
Root Mean Squared Error: 0.471135006621503
R2 Score: 0.9995663665550998
Mean Absolute Error: 0.2838703619940853
Median Absolute Error: 0.16297739510533896
Explained Variance Score: 0.999566393809337
Time taken: 0.510549783706665
====================================================================================================
KNeighborsRegressor
Accuracy: 0.999690607187394
Mean Squared Error: 0.133700207725353
Root Mean Squared Error: 0.3146153065162121
R2 Score: 0.999690607187394
Mean Absolute Error: 0.2268121634618733
Median Absolute Error: 0.16992435922673602
Explained Variance Score: 0.9996909504175697
Time taken: 0.0035009384155273438
====================================================================================================
XGBRegressor
Accuracy: 0.9973284253006156
Mean Squared Error: 1.3469950538183675
Root Mean Squared Error: 1.1513129739162746
R2 Score: 0.9973284253006156
Mean Absolute Error: 0.5870989518202183
Median Absolute Error: 0.3406761042524155
Explained Variance Score: 0.9973396306743728
Time taken: 0.42453837394714355
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 1.98
Fold 1 - Mean Absolute Error (MAE): 1.14
Fold 1 - Root Mean Squared Error (RMSE): 1.41
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 1.94
Fold 2 - Mean Absolute Error (MAE): 1.12
Fold 2 - Root Mean Squared Error (RMSE): 1.39
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 1.83
Fold 3 - Mean Absolute Error (MAE): 1.11
Fold 3 - Root Mean Squared Error (RMSE): 1.35
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 1.98
Fold 4 - Mean Absolute Error (MAE): 1.14
Fold 4 - Root Mean Squared Error (RMSE): 1.41
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 1.95
Fold 5 - Mean Absolute Error (MAE): 1.12
Fold 5 - Root Mean Squared Error (RMSE): 1.40
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 1.94
Mean MAE: 1.13
Mean RMSE: 1.39
Mean time: 0.01 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 2.46
Fold 1 - Mean Absolute Error (MAE): 0.53
Fold 1 - Root Mean Squared Error (RMSE): 1.57
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 6.32
Fold 2 - Mean Absolute Error (MAE): 0.71
Fold 2 - Root Mean Squared Error (RMSE): 2.51
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.37
Fold 3 - Mean Absolute Error (MAE): 0.61
Fold 3 - Root Mean Squared Error (RMSE): 1.84
Fold 3 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.25
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 1.12
Fold 4 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.17
Fold 5 - Mean Absolute Error (MAE): 0.49
Fold 5 - Root Mean Squared Error (RMSE): 1.08
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 2.92
Mean MAE: 0.57
Mean RMSE: 1.62
Mean time: 0.01 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.24
Fold 1 - Mean Absolute Error (MAE): 0.29
Fold 1 - Root Mean Squared Error (RMSE): 0.49
Fold 1 - Time taken: 0.51 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.31
Fold 2 - Mean Absolute Error (MAE): 0.29
Fold 2 - Root Mean Squared Error (RMSE): 0.56
Fold 2 - Time taken: 0.50 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.26
Fold 3 - Mean Absolute Error (MAE): 0.29
Fold 3 - Root Mean Squared Error (RMSE): 0.51
Fold 3 - Time taken: 0.50 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.29
Fold 4 - Mean Absolute Error (MAE): 0.30
Fold 4 - Root Mean Squared Error (RMSE): 0.54
Fold 4 - Time taken: 0.52 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.22
Fold 5 - Mean Absolute Error (MAE): 0.29
Fold 5 - Root Mean Squared Error (RMSE): 0.46
Fold 5 - Time taken: 0.51 seconds
Mean MSE: 0.26
Mean MAE: 0.29
Mean RMSE: 0.51
Mean time: 0.51 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.13
Fold 1 - Mean Absolute Error (MAE): 0.23
Fold 1 - Root Mean Squared Error (RMSE): 0.36
Fold 1 - Time taken: 0.00 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.12
Fold 2 - Mean Absolute Error (MAE): 0.21
Fold 2 - Root Mean Squared Error (RMSE): 0.35
Fold 2 - Time taken: 0.00 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.13
Fold 3 - Mean Absolute Error (MAE): 0.22
Fold 3 - Root Mean Squared Error (RMSE): 0.36
Fold 3 - Time taken: 0.00 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.11
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.34
Fold 4 - Time taken: 0.00 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.12
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.35
Fold 5 - Time taken: 0.00 seconds
Mean MSE: 0.12
Mean MAE: 0.22
Mean RMSE: 0.35
Mean time: 0.00 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.35
Fold 1 - Mean Absolute Error (MAE): 0.59
Fold 1 - Root Mean Squared Error (RMSE): 1.16
Fold 1 - Time taken: 0.32 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.91
Fold 2 - Mean Absolute Error (MAE): 0.57
Fold 2 - Root Mean Squared Error (RMSE): 0.95
Fold 2 - Time taken: 0.30 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.36
Fold 3 - Mean Absolute Error (MAE): 0.62
Fold 3 - Root Mean Squared Error (RMSE): 1.16
Fold 3 - Time taken: 0.30 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.16
Fold 4 - Mean Absolute Error (MAE): 0.62
Fold 4 - Root Mean Squared Error (RMSE): 1.08
Fold 4 - Time taken: 1.31 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.35
Fold 5 - Mean Absolute Error (MAE): 0.62
Fold 5 - Root Mean Squared Error (RMSE): 1.16
Fold 5 - Time taken: 16.46 seconds
Mean MSE: 1.22
Mean MAE: 0.60
Mean RMSE: 1.10
Mean time: 3.74 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Smoothed path loss - (1-8) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 1.98
Fold 1 - Mean Absolute Error (MAE): 1.14
Fold 1 - Root Mean Squared Error (RMSE): 1.41
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 1.94
Fold 2 - Mean Absolute Error (MAE): 1.12
Fold 2 - Root Mean Squared Error (RMSE): 1.39
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 1.83
Fold 3 - Mean Absolute Error (MAE): 1.11
Fold 3 - Root Mean Squared Error (RMSE): 1.35
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 1.98
Fold 4 - Mean Absolute Error (MAE): 1.14
Fold 4 - Root Mean Squared Error (RMSE): 1.41
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 1.95
Fold 5 - Mean Absolute Error (MAE): 1.12
Fold 5 - Root Mean Squared Error (RMSE): 1.40
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 1.94
Mean - Mean Absolute Error (MAE): 1.13
Mean - Root Mean Squared Error (RMSE): 1.39
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 2.56
Fold 1 - Mean Absolute Error (MAE): 0.56
Fold 1 - Root Mean Squared Error (RMSE): 1.60
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 3.72
Fold 2 - Mean Absolute Error (MAE): 0.63
Fold 2 - Root Mean Squared Error (RMSE): 1.93
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.41
Fold 3 - Mean Absolute Error (MAE): 0.61
Fold 3 - Root Mean Squared Error (RMSE): 1.85
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.72
Fold 4 - Mean Absolute Error (MAE): 0.53
Fold 4 - Root Mean Squared Error (RMSE): 1.31
Fold 4 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 2.70
Fold 5 - Mean Absolute Error (MAE): 0.57
Fold 5 - Root Mean Squared Error (RMSE): 1.64
Fold 5 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 2.82
Mean - Mean Absolute Error (MAE): 0.58
Mean - Root Mean Squared Error (RMSE): 1.67
Mean - Time taken: 0.02 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.25
Fold 1 - Mean Absolute Error (MAE): 0.29
Fold 1 - Root Mean Squared Error (RMSE): 0.50
Fold 1 - Time taken: 0.92 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.27
Fold 2 - Mean Absolute Error (MAE): 0.29
Fold 2 - Root Mean Squared Error (RMSE): 0.52
Fold 2 - Time taken: 0.90 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.23
Fold 3 - Mean Absolute Error (MAE): 0.27
Fold 3 - Root Mean Squared Error (RMSE): 0.47
Fold 3 - Time taken: 0.91 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.26
Fold 4 - Mean Absolute Error (MAE): 0.30
Fold 4 - Root Mean Squared Error (RMSE): 0.51
Fold 4 - Time taken: 0.92 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.23
Fold 5 - Mean Absolute Error (MAE): 0.29
Fold 5 - Root Mean Squared Error (RMSE): 0.48
Fold 5 - Time taken: 0.93 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.25
Mean - Mean Absolute Error (MAE): 0.29
Mean - Root Mean Squared Error (RMSE): 0.50
Mean - Time taken: 0.91 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.13
Fold 1 - Mean Absolute Error (MAE): 0.23
Fold 1 - Root Mean Squared Error (RMSE): 0.36
Fold 1 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.12
Fold 2 - Mean Absolute Error (MAE): 0.21
Fold 2 - Root Mean Squared Error (RMSE): 0.35
Fold 2 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.13
Fold 3 - Mean Absolute Error (MAE): 0.22
Fold 3 - Root Mean Squared Error (RMSE): 0.36
Fold 3 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.11
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.34
Fold 4 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.12
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.35
Fold 5 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.12
Mean - Mean Absolute Error (MAE): 0.22
Mean - Root Mean Squared Error (RMSE): 0.35
Mean - Time taken: 0.01 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.35
Fold 1 - Mean Absolute Error (MAE): 0.59
Fold 1 - Root Mean Squared Error (RMSE): 1.16
Fold 1 - Time taken: 15.49 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.91
Fold 2 - Mean Absolute Error (MAE): 0.57
Fold 2 - Root Mean Squared Error (RMSE): 0.95
Fold 2 - Time taken: 14.96 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.36
Fold 3 - Mean Absolute Error (MAE): 0.62
Fold 3 - Root Mean Squared Error (RMSE): 1.16
Fold 3 - Time taken: 15.20 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.16
Fold 4 - Mean Absolute Error (MAE): 0.62
Fold 4 - Root Mean Squared Error (RMSE): 1.08
Fold 4 - Time taken: 11.25 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.35
Fold 5 - Mean Absolute Error (MAE): 0.62
Fold 5 - Root Mean Squared Error (RMSE): 1.16
Fold 5 - Time taken: 8.49 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.22
Mean - Mean Absolute Error (MAE): 0.60
Mean - Root Mean Squared Error (RMSE): 1.10
Mean - Time taken: 13.08 seconds
Results saved to results.xlsx file