# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Scattered path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 8

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:8]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840
...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240

# MinMaxScaler

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler = MinMaxScaler()
sensors_data = scaler.fit_transform(sensors_data)

# Split the data into training and testing sets

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [17]:
X_train

array([[0.64939895, 0.71374411, 0.63715848, ..., 0.70628257, 0.23297583,
        0.36240421],
       [0.371659  , 0.62388101, 0.26637783, ..., 0.66558516, 0.35836923,
        0.65119041],
       [0.80223265, 0.70958588, 0.71892324, ..., 0.38245931, 0.26958494,
        0.2654569 ],
       ...,
       [0.37878048, 0.40050675, 0.27373019, ..., 0.74247439, 0.63904531,
        0.67661285],
       [0.41226104, 0.38637897, 0.53501141, ..., 0.4311818 , 0.67180665,
        0.59319607],
       [0.73349867, 0.63770894, 0.6686133 , ..., 0.4144558 , 0.3424604 ,
        0.30141874]])

In [18]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [20]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [21]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9082257578377962
Mean Squared Error: 40.02737497672028
Root Mean Squared Error: 6.325813371840655
R2 Score: 0.9082257578377962
Mean Absolute Error: 5.127891863509814
Median Absolute Error: 4.326210081633353
Explained Variance Score: 0.9083015014342086
Time taken: 0.002499103546142578
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.77210079806776
Mean Squared Error: 100.49192480705655
Root Mean Squared Error: 10.024448161041983
R2 Score: 0.77210079806776
Mean Absolute Error: 6.566155898019473
Median Absolute Error: 3.730237362180135
Explained Variance Score: 0.7722755757694034
Time taken: 0.008999824523925781
====================================================================================================
RandomForestRegressor
Accuracy: 0.9070817255823158
Mean Squared Error: 41.860695548079676
Root Mean Squared Error: 6.469385933689723
R2 Score: 0.9070817255823158
Mean Absolute Error: 4.86272537349813
Median Absolute Error: 3.6262030204395415
Explained Variance Score: 0.9070851982259933
Time taken: 0.5849990844726562
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9295810783823529
Mean Squared Error: 33.017646168424726
Root Mean Squared Error: 5.733010721748879
R2 Score: 0.9295810783823529
Mean Absolute Error: 4.01206438579087
Median Absolute Error: 2.574503951696991
Explained Variance Score: 0.9296225732603101
Time taken: 0.004999637603759766
====================================================================================================
XGBRegressor
Accuracy: 0.9027858274494062
Mean Squared Error: 44.95786845862195
Root Mean Squared Error: 6.7025231182365586
R2 Score: 0.9027858274494062
Mean Absolute Error: 5.027195212968492
Median Absolute Error: 3.8499362974236853
Explained Variance Score: 0.9028369230901192
Time taken: 0.303999662399292
====================================================================================================

# Cross Validation

In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 40.03
Fold 1 - Mean Absolute Error (MAE): 5.13
Fold 1 - Root Mean Squared Error (RMSE): 6.33
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 38.80
Fold 2 - Mean Absolute Error (MAE): 4.96
Fold 2 - Root Mean Squared Error (RMSE): 6.23
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 39.52
Fold 3 - Mean Absolute Error (MAE): 5.06
Fold 3 - Root Mean Squared Error (RMSE): 6.29
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 40.09
Fold 4 - Mean Absolute Error (MAE): 4.98
Fold 4 - Root Mean Squared Error (RMSE): 6.33
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 38.65
Fold 5 - Mean Absolute Error (MAE): 5.00
Fold 5 - Root Mean Squared Error (RMSE): 6.22
Fold 5 - Time taken: 0.00 seconds
Mean MSE: 39.42
Mean MAE: 5.03
Mean RMSE: 6.28
Mean time: 0.00 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 104.52
Fold 1 - Mean Absolute Error (MAE): 6.73
Fold 1 - Root Mean Squared Error (RMSE): 10.22
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 104.59
Fold 2 - Mean Absolute Error (MAE): 6.52
Fold 2 - Root Mean Squared Error (RMSE): 10.23
Fold 2 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 111.94
Fold 3 - Mean Absolute Error (MAE): 7.04
Fold 3 - Root Mean Squared Error (RMSE): 10.58
Fold 3 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 107.67
Fold 4 - Mean Absolute Error (MAE): 6.90
Fold 4 - Root Mean Squared Error (RMSE): 10.38
Fold 4 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 102.76
Fold 5 - Mean Absolute Error (MAE): 6.55
Fold 5 - Root Mean Squared Error (RMSE): 10.14
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 106.29
Mean MAE: 6.75
Mean RMSE: 10.31
Mean time: 0.01 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 40.65
Fold 1 - Mean Absolute Error (MAE): 4.80
Fold 1 - Root Mean Squared Error (RMSE): 6.38
Fold 1 - Time taken: 0.59 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 36.36
Fold 2 - Mean Absolute Error (MAE): 4.47
Fold 2 - Root Mean Squared Error (RMSE): 6.03
Fold 2 - Time taken: 0.59 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 40.40
Fold 3 - Mean Absolute Error (MAE): 4.73
Fold 3 - Root Mean Squared Error (RMSE): 6.36
Fold 3 - Time taken: 0.58 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 43.29
Fold 4 - Mean Absolute Error (MAE): 4.91
Fold 4 - Root Mean Squared Error (RMSE): 6.58
Fold 4 - Time taken: 0.58 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 39.84
Fold 5 - Mean Absolute Error (MAE): 4.77
Fold 5 - Root Mean Squared Error (RMSE): 6.31
Fold 5 - Time taken: 0.59 seconds
Mean MSE: 40.11
Mean MAE: 4.74
Mean RMSE: 6.33
Mean time: 0.59 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 33.02
Fold 1 - Mean Absolute Error (MAE): 4.01
Fold 1 - Root Mean Squared Error (RMSE): 5.75
Fold 1 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 32.37
Fold 2 - Mean Absolute Error (MAE): 3.88
Fold 2 - Root Mean Squared Error (RMSE): 5.69
Fold 2 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 35.28
Fold 3 - Mean Absolute Error (MAE): 4.19
Fold 3 - Root Mean Squared Error (RMSE): 5.94
Fold 3 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 33.75
Fold 4 - Mean Absolute Error (MAE): 4.00
Fold 4 - Root Mean Squared Error (RMSE): 5.81
Fold 4 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 30.31
Fold 5 - Mean Absolute Error (MAE): 3.84
Fold 5 - Root Mean Squared Error (RMSE): 5.51
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 32.94
Mean MAE: 3.98
Mean RMSE: 5.74
Mean time: 0.01 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 44.96
Fold 1 - Mean Absolute Error (MAE): 5.03
Fold 1 - Root Mean Squared Error (RMSE): 6.71
Fold 1 - Time taken: 0.27 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 41.32
Fold 2 - Mean Absolute Error (MAE): 4.81
Fold 2 - Root Mean Squared Error (RMSE): 6.43
Fold 2 - Time taken: 0.27 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 45.58
Fold 3 - Mean Absolute Error (MAE): 4.97
Fold 3 - Root Mean Squared Error (RMSE): 6.75
Fold 3 - Time taken: 0.26 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 46.87
Fold 4 - Mean Absolute Error (MAE): 5.06
Fold 4 - Root Mean Squared Error (RMSE): 6.85
Fold 4 - Time taken: 0.27 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 46.27
Fold 5 - Mean Absolute Error (MAE): 5.02
Fold 5 - Root Mean Squared Error (RMSE): 6.80
Fold 5 - Time taken: 0.72 seconds
Mean MSE: 45.00
Mean MAE: 4.98
Mean RMSE: 6.71
Mean time: 0.36 seconds
--------------------------------------------------

# Excel File Conversion

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("MinMaxScaler - (1-8) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 40.03
Fold 1 - Mean Absolute Error (MAE): 5.13
Fold 1 - Root Mean Squared Error (RMSE): 6.33
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 38.80
Fold 2 - Mean Absolute Error (MAE): 4.96
Fold 2 - Root Mean Squared Error (RMSE): 6.23
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 39.52
Fold 3 - Mean Absolute Error (MAE): 5.06
Fold 3 - Root Mean Squared Error (RMSE): 6.29
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 40.09
Fold 4 - Mean Absolute Error (MAE): 4.98
Fold 4 - Root Mean Squared Error (RMSE): 6.33
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 38.65
Fold 5 - Mean Absolute Error (MAE): 5.00
Fold 5 - Root Mean Squared Error (RMSE): 6.22
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 39.42
Mean - Mean Absolute Error (MAE): 5.03
Mean - Root Mean Squared Error (RMSE): 6.28
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 100.37
Fold 1 - Mean Absolute Error (MAE): 6.61
Fold 1 - Root Mean Squared Error (RMSE): 10.02
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 98.79
Fold 2 - Mean Absolute Error (MAE): 6.33
Fold 2 - Root Mean Squared Error (RMSE): 9.94
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 110.15
Fold 3 - Mean Absolute Error (MAE): 6.92
Fold 3 - Root Mean Squared Error (RMSE): 10.50
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 105.55
Fold 4 - Mean Absolute Error (MAE): 6.68
Fold 4 - Root Mean Squared Error (RMSE): 10.27
Fold 4 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 103.98
Fold 5 - Mean Absolute Error (MAE): 6.51
Fold 5 - Root Mean Squared Error (RMSE): 10.20
Fold 5 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 103.77
Mean - Mean Absolute Error (MAE): 6.61
Mean - Root Mean Squared Error (RMSE): 10.18
Mean - Time taken: 0.02 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 41.06
Fold 1 - Mean Absolute Error (MAE): 4.84
Fold 1 - Root Mean Squared Error (RMSE): 6.41
Fold 1 - Time taken: 0.86 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 36.84
Fold 2 - Mean Absolute Error (MAE): 4.52
Fold 2 - Root Mean Squared Error (RMSE): 6.07
Fold 2 - Time taken: 0.96 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 40.32
Fold 3 - Mean Absolute Error (MAE): 4.75
Fold 3 - Root Mean Squared Error (RMSE): 6.35
Fold 3 - Time taken: 0.91 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 43.00
Fold 4 - Mean Absolute Error (MAE): 4.91
Fold 4 - Root Mean Squared Error (RMSE): 6.56
Fold 4 - Time taken: 0.96 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 40.14
Fold 5 - Mean Absolute Error (MAE): 4.75
Fold 5 - Root Mean Squared Error (RMSE): 6.34
Fold 5 - Time taken: 0.94 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 40.27
Mean - Mean Absolute Error (MAE): 4.75
Mean - Root Mean Squared Error (RMSE): 6.34
Mean - Time taken: 0.93 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 33.02
Fold 1 - Mean Absolute Error (MAE): 4.01
Fold 1 - Root Mean Squared Error (RMSE): 5.75
Fold 1 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 32.37
Fold 2 - Mean Absolute Error (MAE): 3.88
Fold 2 - Root Mean Squared Error (RMSE): 5.69
Fold 2 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 35.28
Fold 3 - Mean Absolute Error (MAE): 4.19
Fold 3 - Root Mean Squared Error (RMSE): 5.94
Fold 3 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 33.75
Fold 4 - Mean Absolute Error (MAE): 4.00
Fold 4 - Root Mean Squared Error (RMSE): 5.81
Fold 4 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 30.31
Fold 5 - Mean Absolute Error (MAE): 3.84
Fold 5 - Root Mean Squared Error (RMSE): 5.51
Fold 5 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 32.94
Mean - Mean Absolute Error (MAE): 3.98
Mean - Root Mean Squared Error (RMSE): 5.74
Mean - Time taken: 0.01 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 44.96
Fold 1 - Mean Absolute Error (MAE): 5.03
Fold 1 - Root Mean Squared Error (RMSE): 6.71
Fold 1 - Time taken: 0.86 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 41.32
Fold 2 - Mean Absolute Error (MAE): 4.81
Fold 2 - Root Mean Squared Error (RMSE): 6.43
Fold 2 - Time taken: 1.31 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 45.58
Fold 3 - Mean Absolute Error (MAE): 4.97
Fold 3 - Root Mean Squared Error (RMSE): 6.75
Fold 3 - Time taken: 1.18 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 46.87
Fold 4 - Mean Absolute Error (MAE): 5.06
Fold 4 - Root Mean Squared Error (RMSE): 6.85
Fold 4 - Time taken: 1.58 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 46.27
Fold 5 - Mean Absolute Error (MAE): 5.02
Fold 5 - Root Mean Squared Error (RMSE): 6.80
Fold 5 - Time taken: 2.14 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 45.00
Mean - Mean Absolute Error (MAE): 4.98
Mean - Root Mean Squared Error (RMSE): 6.71
Mean - Time taken: 1.41 seconds
Results saved to results.xlsx file