# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Smoothed path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 32

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:32]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor23,sensor24,sensor25,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,100.697724,129.781474,92.811742,124.387133,77.021332,116.684638,116.193296,140.177973,105.574867,132.360602
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,100.697724,129.781474,92.811742,124.387133,77.021332,116.684638,116.193296,140.177973,105.574867,132.360602
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,100.697724,129.781474,92.811742,124.387133,77.021332,116.684638,116.193296,140.177973,105.574867,132.360602
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,100.697724,129.781474,92.811742,124.387133,77.021332,116.684638,116.193296,140.177973,105.574867,132.360602
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,100.697724,129.781474,92.811742,124.387133,77.021332,116.684638,116.193296,140.177973,105.574867,132.360602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,123.635019,105.756975,119.089740,101.618444,101.593972,72.265306,145.089528,131.222098,130.528525,110.870276
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,123.635019,105.756975,119.089740,101.618444,101.593972,72.265306,145.089528,131.222098,130.528525,110.870276
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,123.635019,105.756975,119.089740,101.618444,101.593972,72.265306,145.089528,131.222098,130.528525,110.870276
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,123.635019,105.756975,119.089740,101.618444,101.593972,72.265306,145.089528,131.222098,130.528525,110.870276
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,123.635019,105.756975,119.089740,101.618444,101.593972,72.265306,145.089528,131.222098,130.528525,110.870276

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor23,sensor24,sensor25,sensor26,sensor27,sensor28,sensor29,sensor30,sensor31,sensor32
233,137.881517,153.165243,115.871574,137.406585,112.526032,135.466550,71.723841,110.006074,136.787768,148.064769,...,69.304850,108.862294,130.896040,148.912523,112.325427,134.618144,99.182363,125.299656,67.888557,106.157627
433,121.592208,139.058026,86.335605,112.792428,130.389895,146.267373,99.826221,119.987946,119.634796,130.704687,...,86.616492,112.839707,110.832870,130.146585,82.132326,111.771354,119.753773,138.747628,96.401894,119.289397
1430,145.771325,144.778557,117.656261,118.072187,126.463228,129.171448,86.779440,90.997365,140.201692,140.003560,...,84.863571,86.550922,135.040798,139.904263,114.469757,116.799338,117.070023,118.520987,89.656149,89.649395
307,127.945292,147.421209,113.727319,135.577414,104.027441,126.791389,81.781185,113.726384,127.379462,140.019466,...,78.954083,110.928583,120.146032,139.456232,110.285866,131.956755,94.651371,120.804895,76.016138,107.558477
2197,140.479449,130.043474,130.979969,115.610718,122.947593,107.437010,107.938768,88.593358,134.119687,126.435584,...,104.427958,83.678985,135.253337,123.154292,125.257622,112.011506,115.125416,98.011637,103.963811,82.876846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,131.484235,128.208485,110.374820,108.586940,125.997951,121.476007,103.909611,99.945705,125.277444,123.634429,...,95.500772,94.558253,123.219480,120.439231,107.865380,104.233936,117.052606,115.195214,100.452787,96.427228
1095,127.067786,131.636548,87.134422,99.243018,140.639940,147.382136,111.281736,118.231354,122.493099,125.273887,...,101.655257,109.060746,113.945872,124.286467,87.250573,95.355525,133.276668,138.020912,109.119850,118.067270
1130,123.972924,130.783089,84.240653,97.925160,144.913317,150.133795,114.828089,121.051632,119.591640,122.401914,...,103.740616,111.805489,112.386660,120.447516,81.773405,92.099103,136.167093,140.220213,116.046318,121.363806
1294,117.190655,120.592002,96.872234,101.981039,129.046835,133.089505,113.339273,117.095254,111.655741,113.163124,...,103.817703,109.501359,106.913926,112.105903,93.405811,98.452526,120.967684,124.794854,106.981332,113.762175
860,139.956869,150.417225,118.141071,130.418639,114.598147,127.566352,81.158577,98.930350,137.830975,141.822428,...,76.764466,97.500142,134.643056,144.324855,117.371826,127.524990,107.167954,117.892697,75.535423,98.278125

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.998936846617993
Mean Squared Error: 0.46206845512086164
Root Mean Squared Error: 0.6796141714309559
R2 Score: 0.998936846617993
Mean Absolute Error: 0.5448761794278384
Median Absolute Error: 0.46360050582504897
Explained Variance Score: 0.9989376248543375
Time taken: 0.00550079345703125
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.9973277618936519
Mean Squared Error: 1.6550955222484267
Root Mean Squared Error: 1.2395163193198024
R2 Score: 0.9973277618936519
Mean Absolute Error: 0.48331474460047225
Median Absolute Error: 0.3185783641438344
Explained Variance Score: 0.9973316827142246
Time taken: 0.028000354766845703
====================================================================================================
RandomForestRegressor
Accuracy: 0.9994514650898045
Mean Squared Error: 0.30146053844103055
Root Mean Squared Error: 0.5375565188444685
R2 Score: 0.9994514650898045
Mean Absolute Error: 0.24523410746193489
Median Absolute Error: 0.11832865422735998
Explained Variance Score: 0.9994517020868837
Time taken: 1.549497365951538
====================================================================================================
KNeighborsRegressor
Accuracy: 0.999812112846136
Mean Squared Error: 0.07009778125473029
Root Mean Squared Error: 0.22895329107641774
R2 Score: 0.999812112846136
Mean Absolute Error: 0.15539035294929437
Median Absolute Error: 0.1271499103618249
Explained Variance Score: 0.9998141719058076
Time taken: 0.05299997329711914
====================================================================================================
XGBRegressor
Accuracy: 0.9975038223813576
Mean Squared Error: 1.2742428662835503
Root Mean Squared Error: 1.1184371563625866
R2 Score: 0.9975038223813576
Mean Absolute Error: 0.5501105851959975
Median Absolute Error: 0.34221851405980885
Explained Variance Score: 0.9975140035637292
Time taken: 0.3905003070831299
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.46
Fold 1 - Mean Absolute Error (MAE): 0.54
Fold 1 - Root Mean Squared Error (RMSE): 0.68
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.48
Fold 2 - Mean Absolute Error (MAE): 0.55
Fold 2 - Root Mean Squared Error (RMSE): 0.69
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.50
Fold 3 - Mean Absolute Error (MAE): 0.58
Fold 3 - Root Mean Squared Error (RMSE): 0.71
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.48
Fold 4 - Mean Absolute Error (MAE): 0.55
Fold 4 - Root Mean Squared Error (RMSE): 0.69
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.47
Fold 5 - Mean Absolute Error (MAE): 0.55
Fold 5 - Root Mean Squared Error (RMSE): 0.69
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 0.48
Mean MAE: 0.55
Mean RMSE: 0.69
Mean time: 0.01 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 4.07
Fold 1 - Mean Absolute Error (MAE): 0.65
Fold 1 - Root Mean Squared Error (RMSE): 2.02
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 0.63
Fold 2 - Mean Absolute Error (MAE): 0.47
Fold 2 - Root Mean Squared Error (RMSE): 0.80
Fold 2 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 5.03
Fold 3 - Mean Absolute Error (MAE): 0.66
Fold 3 - Root Mean Squared Error (RMSE): 2.24
Fold 3 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.19
Fold 4 - Mean Absolute Error (MAE): 0.49
Fold 4 - Root Mean Squared Error (RMSE): 1.09
Fold 4 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.71
Fold 5 - Mean Absolute Error (MAE): 0.47
Fold 5 - Root Mean Squared Error (RMSE): 0.84
Fold 5 - Time taken: 0.03 seconds
Mean MSE: 2.33
Mean MAE: 0.55
Mean RMSE: 1.40
Mean time: 0.03 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.30
Fold 1 - Mean Absolute Error (MAE): 0.24
Fold 1 - Root Mean Squared Error (RMSE): 0.55
Fold 1 - Time taken: 1.55 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.12
Fold 2 - Mean Absolute Error (MAE): 0.20
Fold 2 - Root Mean Squared Error (RMSE): 0.35
Fold 2 - Time taken: 1.94 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.30
Fold 3 - Mean Absolute Error (MAE): 0.25
Fold 3 - Root Mean Squared Error (RMSE): 0.55
Fold 3 - Time taken: 2.68 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.14
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.37
Fold 4 - Time taken: 2.64 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.15
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.39
Fold 5 - Time taken: 2.69 seconds
Mean MSE: 0.20
Mean MAE: 0.23
Mean RMSE: 0.44
Mean time: 2.30 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.06
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.24
Fold 1 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.08
Fold 2 - Mean Absolute Error (MAE): 0.16
Fold 2 - Root Mean Squared Error (RMSE): 0.28
Fold 2 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.09
Fold 3 - Mean Absolute Error (MAE): 0.17
Fold 3 - Root Mean Squared Error (RMSE): 0.30
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.08
Fold 4 - Mean Absolute Error (MAE): 0.17
Fold 4 - Root Mean Squared Error (RMSE): 0.27
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.08
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.28
Fold 5 - Time taken: 0.06 seconds
Mean MSE: 0.08
Mean MAE: 0.16
Mean RMSE: 0.28
Mean time: 0.06 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.27
Fold 1 - Mean Absolute Error (MAE): 0.55
Fold 1 - Root Mean Squared Error (RMSE): 1.13
Fold 1 - Time taken: 6.47 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.89
Fold 2 - Mean Absolute Error (MAE): 0.56
Fold 2 - Root Mean Squared Error (RMSE): 0.94
Fold 2 - Time taken: 6.11 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.14
Fold 3 - Mean Absolute Error (MAE): 0.53
Fold 3 - Root Mean Squared Error (RMSE): 1.07
Fold 3 - Time taken: 6.13 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.70
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 0.84
Fold 4 - Time taken: 6.18 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.46
Fold 5 - Mean Absolute Error (MAE): 0.57
Fold 5 - Root Mean Squared Error (RMSE): 1.21
Fold 5 - Time taken: 6.11 seconds
Mean MSE: 1.09
Mean MAE: 0.54
Mean RMSE: 1.04
Mean time: 6.20 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Smoothed path loss - (1-32) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.46
Fold 1 - Mean Absolute Error (MAE): 0.54
Fold 1 - Root Mean Squared Error (RMSE): 0.68
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.48
Fold 2 - Mean Absolute Error (MAE): 0.55
Fold 2 - Root Mean Squared Error (RMSE): 0.69
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.50
Fold 3 - Mean Absolute Error (MAE): 0.58
Fold 3 - Root Mean Squared Error (RMSE): 0.71
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.48
Fold 4 - Mean Absolute Error (MAE): 0.55
Fold 4 - Root Mean Squared Error (RMSE): 0.69
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.47
Fold 5 - Mean Absolute Error (MAE): 0.55
Fold 5 - Root Mean Squared Error (RMSE): 0.69
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.48
Mean - Mean Absolute Error (MAE): 0.55
Mean - Root Mean Squared Error (RMSE): 0.69
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 2.72
Fold 1 - Mean Absolute Error (MAE): 0.58
Fold 1 - Root Mean Squared Error (RMSE): 1.65
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 0.70
Fold 2 - Mean Absolute Error (MAE): 0.49
Fold 2 - Root Mean Squared Error (RMSE): 0.83
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.29
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 1.81
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.67
Fold 4 - Mean Absolute Error (MAE): 0.49
Fold 4 - Root Mean Squared Error (RMSE): 1.29
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.68
Fold 5 - Mean Absolute Error (MAE): 0.48
Fold 5 - Root Mean Squared Error (RMSE): 0.83
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.81
Mean - Mean Absolute Error (MAE): 0.51
Mean - Root Mean Squared Error (RMSE): 1.28
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.32
Fold 1 - Mean Absolute Error (MAE): 0.25
Fold 1 - Root Mean Squared Error (RMSE): 0.57
Fold 1 - Time taken: 2.69 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.15
Fold 2 - Mean Absolute Error (MAE): 0.21
Fold 2 - Root Mean Squared Error (RMSE): 0.39
Fold 2 - Time taken: 2.70 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.35
Fold 3 - Mean Absolute Error (MAE): 0.26
Fold 3 - Root Mean Squared Error (RMSE): 0.59
Fold 3 - Time taken: 2.70 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.12
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.35
Fold 4 - Time taken: 2.71 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.14
Fold 5 - Mean Absolute Error (MAE): 0.21
Fold 5 - Root Mean Squared Error (RMSE): 0.37
Fold 5 - Time taken: 2.70 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.22
Mean - Mean Absolute Error (MAE): 0.23
Mean - Root Mean Squared Error (RMSE): 0.45
Mean - Time taken: 2.70 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.06
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.24
Fold 1 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.08
Fold 2 - Mean Absolute Error (MAE): 0.16
Fold 2 - Root Mean Squared Error (RMSE): 0.28
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.09
Fold 3 - Mean Absolute Error (MAE): 0.17
Fold 3 - Root Mean Squared Error (RMSE): 0.30
Fold 3 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.08
Fold 4 - Mean Absolute Error (MAE): 0.17
Fold 4 - Root Mean Squared Error (RMSE): 0.27
Fold 4 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.08
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.28
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.08
Mean - Mean Absolute Error (MAE): 0.16
Mean - Root Mean Squared Error (RMSE): 0.28
Mean - Time taken: 0.05 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.27
Fold 1 - Mean Absolute Error (MAE): 0.55
Fold 1 - Root Mean Squared Error (RMSE): 1.13
Fold 1 - Time taken: 7.06 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.89
Fold 2 - Mean Absolute Error (MAE): 0.56
Fold 2 - Root Mean Squared Error (RMSE): 0.94
Fold 2 - Time taken: 5.91 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.14
Fold 3 - Mean Absolute Error (MAE): 0.53
Fold 3 - Root Mean Squared Error (RMSE): 1.07
Fold 3 - Time taken: 6.01 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.70
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 0.84
Fold 4 - Time taken: 6.10 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.46
Fold 5 - Mean Absolute Error (MAE): 0.57
Fold 5 - Root Mean Squared Error (RMSE): 1.21
Fold 5 - Time taken: 5.82 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.09
Mean - Mean Absolute Error (MAE): 0.54
Mean - Root Mean Squared Error (RMSE): 1.04
Mean - Time taken: 6.18 seconds
Results saved to results.xlsx file