# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_scattered_48_reg_frontback_random.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,99.531742,113.249339,103.217626,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,98.810013,101.878517,104.363022,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,94.813690,107.732324,105.612958,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,105.018314,104.822431,101.264143,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,106.276715,100.853621,105.035107,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,108.898729,120.478896,116.600259,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,96.454590,123.164933,106.694996,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,103.114188,117.380927,101.377838,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,110.786983,116.579398,107.851790,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,100.983003,118.492095,104.809426,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,99.531742,113.249339,103.217626,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,98.810013,101.878517,104.363022,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,94.813690,107.732324,105.612958,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,105.018314,104.822431,101.264143,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,106.276715,100.853621,105.035107,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,108.898729,120.478896,116.600259,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,96.454590,123.164933,106.694996,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,103.114188,117.380927,101.377838,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,110.786983,116.579398,107.851790,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,100.983003,118.492095,104.809426,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

### Concatenating Dataframes

In [13]:
raw_data = pd.concat([sensors_data, position_data], axis = 1)
raw_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48,Pos X,Pos Y,Pos Z
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931,-45.581275,30.239368,-60.00
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519,-45.188830,30.181623,-59.96
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710,-44.791865,30.131806,-59.92
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962,-44.390422,30.089935,-59.88
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510,-43.984540,30.056029,-59.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172,-59.939858,51.788725,37.52
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770,-59.963718,51.389997,37.56
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789,-59.981583,50.990713,37.60
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650,-59.993448,50.591032,37.64
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339,-59.999315,50.191116,37.68

# Initializing data into X and y

In [14]:
X = sensors_data
y = position_data

# Tuning Random Forest Regressor

# Importing Libraries

In [15]:
import time
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

# Initializing Kfold

In [16]:
kfold = KFold(n_splits=20, shuffle=True, random_state=42)

# Getting Parameters

In [17]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
print(rf.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

# Adding Random Parameters

In [18]:
param_grid = {
    'ccp_alpha': [0.0],
    'max_depth': [None, 5, 10, 15],
    'max_features': ['auto', 'sqrt', 'log2', 0.25, 0.5, 0.75, 1.0],
    'max_leaf_nodes': [None, 5, 10, 20],
    'max_samples': [None],
    'min_impurity_decrease': [0.0, 0.01, 0.1],
    'min_samples_leaf': [1, 2, 4, 8],
    'min_samples_split': [2, 5, 10, 20],
    'min_weight_fraction_leaf': [0.0, 0.1, 0.2],
    'n_estimators': [100, 200, 300]
}

# Define hyperparameters to search for each model

'max_features': ['sqrt']
'max_depth': [150],
'n_estimators': [500]
'min_weight_fraction_leaf': [0.0]
'min_samples_split': [2]
'min_samples_leaf': [1]
'max_leaf_nodes': [None]
'min_impurity_decrease': [0.0]
'min_weight_fraction_leaf': [0.0]

In [19]:
models_params = [(RandomForestRegressor(),
                  
{
    'ccp_alpha': [0.0],
    'max_depth': [None, 5, 10, 15],
    'max_features': ['auto', 'sqrt', 'log2', 0.25, 0.5, 0.75, 1.0],
    'max_leaf_nodes': [None, 5, 10, 20],
    'max_samples': [None],
    'min_impurity_decrease': [0.0, 0.01, 0.1],
    'min_samples_leaf': [1, 2, 4, 8],
    'min_samples_split': [2, 5, 10, 20],
    'min_weight_fraction_leaf': [0.0, 0.1, 0.2],
    'n_estimators': [100, 200, 300]
    
}
                  
                 )]

In [20]:
# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": [],
    "Best Parameters": []
}

# Loop over models and perform hyperparameter tuning

In [21]:
for model, params in models_params:
    
    #GridSearchCV
    
    
    start_time = time.time()
    grid_search = GridSearchCV(model, params, cv=kfold, scoring='neg_mean_squared_error', n_jobs=-1)
    grid_search.fit(X, y)
    end_time = time.time()
    results_dict["Model"].append(str(model).split('(')[0])
    results_dict["Fold"].append("Grid Search")
    results_dict["Mean Squared Error (MSE)"].append(-grid_search.best_score_)
    results_dict["Mean Absolute Error (MAE)"].append(mean_absolute_error(y, grid_search.predict(X)))
    results_dict["Root Mean Squared Error (RMSE)"].append(np.sqrt(-grid_search.best_score_))
    results_dict["Time taken"].append(end_time - start_time)
    results_dict["Best Parameters"].append(grid_search.best_params_)
    
    #RandomizedSearchCV
    
    
    start_time = time.time()
    random_search = RandomizedSearchCV(model, params, cv=kfold, scoring='neg_mean_squared_error', n_jobs=-1)
    random_search.fit(X, y)
    end_time = time.time()
    results_dict["Model"].append(str(model).split('(')[0])
    results_dict["Fold"].append("Randomized Search")
    results_dict["Mean Squared Error (MSE)"].append(-random_search.best_score_)
    results_dict["Mean Absolute Error (MAE)"].append(mean_absolute_error(y, random_search.predict(X)))
    results_dict["Root Mean Squared Error (RMSE)"].append(np.sqrt(-random_search.best_score_))
    results_dict["Time taken"].append(end_time - start_time)
    results_dict["Best Parameters"].append(random_search.best_params_)

C:\Users\nafem\anaconda3\envs\gpu\lib\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

# Display Results

In [22]:
# set display options
pd.set_option("display.max_columns", None)  # show all columns
pd.set_option("display.width", None)  # auto-adjust column width
pd.set_option("display.max_colwidth", None)  # show full column contents

# Create a pandas dataframe from the results dictionary
results_df = pd.DataFrame(results_dict)

# Group the results by model and fold, and display the best parameters for each group
grouped_results = results_df.groupby(["Model", "Fold"]).apply(lambda x: x.loc[x["Mean Squared Error (MSE)"].idxmin()]).reset_index(drop=True)

# Create a new column with the Best Parameters in full sentence format
grouped_results["Full Parameters"] = grouped_results["Best Parameters"].apply(lambda x: ', '.join(['{}={}'.format(key, val) for key, val in x.items()]))

# Display the grouped results with the Full Parameters column
display(grouped_results[["Model", "Fold", "Full Parameters", "Mean Squared Error (MSE)", "Mean Absolute Error (MAE)", "Root Mean Squared Error (RMSE)", "Time taken"]])

,Model,Fold,Full Parameters,Mean Squared Error (MSE),Mean Absolute Error (MAE),Root Mean Squared Error (RMSE),Time taken
0,RandomForestRegressor,Grid Search,min_weight_fraction_leaf=0.0,19.188238,1.265412,4.380438,25.125115
1,RandomForestRegressor,Randomized Search,min_weight_fraction_leaf=0.0,19.077634,1.292691,4.367795,49.493733

# Best Parameters

'max_features': ['sqrt']
'max_depth': [150],
'n_estimators': [500]
'min_weight_fraction_leaf': [0.0]
'min_samples_split': [2]
'min_samples_leaf': [1]
'max_leaf_nodes': [None]
'min_impurity_decrease': [0.0]
'min_weight_fraction_leaf': [0.0]