# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Smoothed path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 40

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:40]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor31,sensor32,sensor33,sensor34,sensor35,sensor36,sensor37,sensor38,sensor39,sensor40
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,105.574867,132.360602,101.770490,114.369956,80.271731,98.526806,123.646651,132.874522,107.203207,119.753930
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,105.574867,132.360602,101.770490,114.369956,80.271731,98.526806,123.646651,132.874522,107.203207,119.753930
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,105.574867,132.360602,101.770490,114.369956,80.271731,98.526806,123.646651,132.874522,107.203207,119.753930
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,105.574867,132.360602,101.770490,114.369956,80.271731,98.526806,123.646651,132.874522,107.203207,119.753930
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,105.574867,132.360602,101.770490,114.369956,80.271731,98.526806,123.646651,132.874522,107.203207,119.753930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,130.528525,110.870276,115.905672,107.615082,83.533776,65.117097,141.521855,136.408632,119.411902,110.280775
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,130.528525,110.870276,115.905672,107.615082,83.533776,65.117097,141.521855,136.408632,119.411902,110.280775
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,130.528525,110.870276,115.905672,107.615082,83.533776,65.117097,141.521855,136.408632,119.411902,110.280775
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,130.528525,110.870276,115.905672,107.615082,83.533776,65.117097,141.521855,136.408632,119.411902,110.280775
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,130.528525,110.870276,115.905672,107.615082,83.533776,65.117097,141.521855,136.408632,119.411902,110.280775

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor31,sensor32,sensor33,sensor34,sensor35,sensor36,sensor37,sensor38,sensor39,sensor40
233,137.881517,153.165243,115.871574,137.406585,112.526032,135.466550,71.723841,110.006074,136.787768,148.064769,...,67.888557,106.157627,135.247588,143.382590,109.856749,121.034284,108.036492,118.008606,66.017527,85.496544
433,121.592208,139.058026,86.335605,112.792428,130.389895,146.267373,99.826221,119.987946,119.634796,130.704687,...,96.401894,119.289397,116.849749,126.052255,78.793653,92.607596,126.931078,133.715512,94.584263,103.701592
1430,145.771325,144.778557,117.656261,118.072187,126.463228,129.171448,86.779440,90.997365,140.201692,140.003560,...,89.656149,89.649395,138.048030,138.037631,106.243499,105.860157,117.274208,118.105024,70.534530,72.403997
307,127.945292,147.421209,113.727319,135.577414,104.027441,126.791389,81.781185,113.726384,127.379462,140.019466,...,76.016138,107.558477,126.672475,132.946649,110.889351,118.804191,101.840129,111.989294,76.606800,93.187422
2197,140.479449,130.043474,130.979969,115.610718,122.947593,107.437010,107.938768,88.593358,134.119687,126.435584,...,103.963811,82.876846,129.546345,125.232401,113.327008,109.706135,108.549839,98.774800,86.151970,77.977558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,131.484235,128.208485,110.374820,108.586940,125.997951,121.476007,103.909611,99.945705,125.277444,123.634429,...,100.452787,96.427228,120.527422,121.336203,96.349344,97.268626,116.551726,114.029768,87.653681,86.493576
1095,127.067786,131.636548,87.134422,99.243018,140.639940,147.382136,111.281736,118.231354,122.493099,125.273887,...,109.119850,118.067270,117.374618,121.083466,70.523565,78.750176,135.090119,137.766403,101.760375,106.238368
1130,123.972924,130.783089,84.240653,97.925160,144.913317,150.133795,114.828089,121.051632,119.591640,122.401914,...,116.046318,121.363806,116.350863,117.409915,68.225656,74.812430,136.096418,140.402008,107.283387,110.861847
1294,117.190655,120.592002,96.872234,101.981039,129.046835,133.089505,113.339273,117.095254,111.655741,113.163124,...,106.981332,113.762175,107.291071,108.007491,83.256344,86.443474,121.867642,123.483278,104.802458,106.182501
860,139.956869,150.417225,118.141071,130.418639,114.598147,127.566352,81.158577,98.930350,137.830975,141.822428,...,75.535423,98.278125,136.877646,139.509094,110.970244,118.078170,110.140498,113.319181,68.627831,78.371937

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9991047422337188
Mean Squared Error: 0.3913579894204065
Root Mean Squared Error: 0.6254527548900469
R2 Score: 0.9991047422337188
Mean Absolute Error: 0.4993311912881205
Median Absolute Error: 0.4215028715225013
Explained Variance Score: 0.9991057754989457
Time taken: 0.005999326705932617
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.997581031588696
Mean Squared Error: 1.3821337891652814
Root Mean Squared Error: 1.1554068383634803
R2 Score: 0.997581031588696
Mean Absolute Error: 0.5002877006710816
Median Absolute Error: 0.32251779114830254
Explained Variance Score: 0.9975857769171674
Time taken: 0.03350019454956055
====================================================================================================
RandomForestRegressor
Accuracy: 0.9994065159353381
Mean Squared Error: 0.29002475599754024
Root Mean Squared Error: 0.5313687657792724
R2 Score: 0.9994065159353381
Mean Absolute Error: 0.23319407754603816
Median Absolute Error: 0.10867830356071077
Explained Variance Score: 0.9994071640130012
Time taken: 1.9164974689483643
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9998340433789373
Mean Squared Error: 0.06289968309944036
Root Mean Squared Error: 0.2168848961064185
R2 Score: 0.9998340433789373
Mean Absolute Error: 0.14921816360649723
Median Absolute Error: 0.12378457847720821
Explained Variance Score: 0.9998344847645751
Time taken: 0.0605006217956543
====================================================================================================
XGBRegressor
Accuracy: 0.9973147138097689
Mean Squared Error: 1.2092608694213165
Root Mean Squared Error: 1.0828081324462426
R2 Score: 0.9973147138097689
Mean Absolute Error: 0.5132811941743367
Median Absolute Error: 0.316387814720386
Explained Variance Score: 0.997331862738757
Time taken: 0.4699990749359131
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.39
Fold 1 - Mean Absolute Error (MAE): 0.50
Fold 1 - Root Mean Squared Error (RMSE): 0.63
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.41
Fold 2 - Mean Absolute Error (MAE): 0.50
Fold 2 - Root Mean Squared Error (RMSE): 0.64
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.42
Fold 3 - Mean Absolute Error (MAE): 0.53
Fold 3 - Root Mean Squared Error (RMSE): 0.65
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.41
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 0.64
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.38
Fold 5 - Mean Absolute Error (MAE): 0.49
Fold 5 - Root Mean Squared Error (RMSE): 0.62
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 0.40
Mean MAE: 0.50
Mean RMSE: 0.63
Mean time: 0.01 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.64
Fold 1 - Mean Absolute Error (MAE): 0.44
Fold 1 - Root Mean Squared Error (RMSE): 0.80
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.64
Fold 2 - Mean Absolute Error (MAE): 0.54
Fold 2 - Root Mean Squared Error (RMSE): 1.63
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.83
Fold 3 - Mean Absolute Error (MAE): 0.56
Fold 3 - Root Mean Squared Error (RMSE): 1.96
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.85
Fold 4 - Mean Absolute Error (MAE): 0.46
Fold 4 - Root Mean Squared Error (RMSE): 0.92
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 2.35
Fold 5 - Mean Absolute Error (MAE): 0.55
Fold 5 - Root Mean Squared Error (RMSE): 1.53
Fold 5 - Time taken: 0.04 seconds
Mean MSE: 2.06
Mean MAE: 0.51
Mean RMSE: 1.37
Mean time: 0.04 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.34
Fold 1 - Mean Absolute Error (MAE): 0.23
Fold 1 - Root Mean Squared Error (RMSE): 0.59
Fold 1 - Time taken: 1.91 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.53
Fold 2 - Mean Absolute Error (MAE): 0.23
Fold 2 - Root Mean Squared Error (RMSE): 0.73
Fold 2 - Time taken: 2.89 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.29
Fold 3 - Mean Absolute Error (MAE): 0.24
Fold 3 - Root Mean Squared Error (RMSE): 0.54
Fold 3 - Time taken: 3.24 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.14
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.37
Fold 4 - Time taken: 3.23 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.16
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.39
Fold 5 - Time taken: 3.28 seconds
Mean MSE: 0.29
Mean MAE: 0.23
Mean RMSE: 0.52
Mean time: 2.91 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.23
Fold 1 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.08
Fold 2 - Mean Absolute Error (MAE): 0.16
Fold 2 - Root Mean Squared Error (RMSE): 0.28
Fold 2 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.08
Fold 3 - Mean Absolute Error (MAE): 0.16
Fold 3 - Root Mean Squared Error (RMSE): 0.28
Fold 3 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.07
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.26
Fold 4 - Time taken: 0.04 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.07
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.27
Fold 5 - Time taken: 0.04 seconds
Mean MSE: 0.07
Mean MAE: 0.16
Mean RMSE: 0.27
Mean time: 0.06 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.21
Fold 1 - Mean Absolute Error (MAE): 0.51
Fold 1 - Root Mean Squared Error (RMSE): 1.10
Fold 1 - Time taken: 6.49 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.72
Fold 2 - Mean Absolute Error (MAE): 0.51
Fold 2 - Root Mean Squared Error (RMSE): 0.85
Fold 2 - Time taken: 6.24 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.23
Fold 3 - Mean Absolute Error (MAE): 0.55
Fold 3 - Root Mean Squared Error (RMSE): 1.11
Fold 3 - Time taken: 6.10 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.70
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 0.84
Fold 4 - Time taken: 6.10 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.25
Fold 5 - Mean Absolute Error (MAE): 0.53
Fold 5 - Root Mean Squared Error (RMSE): 1.12
Fold 5 - Time taken: 6.27 seconds
Mean MSE: 1.02
Mean MAE: 0.52
Mean RMSE: 1.00
Mean time: 6.24 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Smoothed path loss - (1-40) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.39
Fold 1 - Mean Absolute Error (MAE): 0.50
Fold 1 - Root Mean Squared Error (RMSE): 0.63
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.41
Fold 2 - Mean Absolute Error (MAE): 0.50
Fold 2 - Root Mean Squared Error (RMSE): 0.64
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.42
Fold 3 - Mean Absolute Error (MAE): 0.53
Fold 3 - Root Mean Squared Error (RMSE): 0.65
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.41
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 0.64
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.38
Fold 5 - Mean Absolute Error (MAE): 0.49
Fold 5 - Root Mean Squared Error (RMSE): 0.62
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.40
Mean - Mean Absolute Error (MAE): 0.50
Mean - Root Mean Squared Error (RMSE): 0.63
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.62
Fold 1 - Mean Absolute Error (MAE): 0.51
Fold 1 - Root Mean Squared Error (RMSE): 1.27
Fold 1 - Time taken: 0.06 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.70
Fold 2 - Mean Absolute Error (MAE): 0.56
Fold 2 - Root Mean Squared Error (RMSE): 1.64
Fold 2 - Time taken: 0.06 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 5.41
Fold 3 - Mean Absolute Error (MAE): 0.66
Fold 3 - Root Mean Squared Error (RMSE): 2.33
Fold 3 - Time taken: 0.06 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 1.34
Fold 4 - Mean Absolute Error (MAE): 0.53
Fold 4 - Root Mean Squared Error (RMSE): 1.16
Fold 4 - Time taken: 0.06 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.95
Fold 5 - Mean Absolute Error (MAE): 0.51
Fold 5 - Root Mean Squared Error (RMSE): 1.40
Fold 5 - Time taken: 0.06 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 2.61
Mean - Mean Absolute Error (MAE): 0.56
Mean - Root Mean Squared Error (RMSE): 1.56
Mean - Time taken: 0.06 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.38
Fold 1 - Mean Absolute Error (MAE): 0.25
Fold 1 - Root Mean Squared Error (RMSE): 0.61
Fold 1 - Time taken: 3.28 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.53
Fold 2 - Mean Absolute Error (MAE): 0.24
Fold 2 - Root Mean Squared Error (RMSE): 0.73
Fold 2 - Time taken: 3.29 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.36
Fold 3 - Mean Absolute Error (MAE): 0.25
Fold 3 - Root Mean Squared Error (RMSE): 0.60
Fold 3 - Time taken: 3.32 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.10
Fold 4 - Mean Absolute Error (MAE): 0.19
Fold 4 - Root Mean Squared Error (RMSE): 0.32
Fold 4 - Time taken: 3.29 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.13
Fold 5 - Mean Absolute Error (MAE): 0.20
Fold 5 - Root Mean Squared Error (RMSE): 0.37
Fold 5 - Time taken: 3.25 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.30
Mean - Mean Absolute Error (MAE): 0.23
Mean - Root Mean Squared Error (RMSE): 0.53
Mean - Time taken: 3.29 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.05
Fold 1 - Mean Absolute Error (MAE): 0.15
Fold 1 - Root Mean Squared Error (RMSE): 0.23
Fold 1 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.08
Fold 2 - Mean Absolute Error (MAE): 0.16
Fold 2 - Root Mean Squared Error (RMSE): 0.28
Fold 2 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.08
Fold 3 - Mean Absolute Error (MAE): 0.16
Fold 3 - Root Mean Squared Error (RMSE): 0.28
Fold 3 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.07
Fold 4 - Mean Absolute Error (MAE): 0.16
Fold 4 - Root Mean Squared Error (RMSE): 0.26
Fold 4 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.07
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.27
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.07
Mean - Mean Absolute Error (MAE): 0.16
Mean - Root Mean Squared Error (RMSE): 0.27
Mean - Time taken: 0.06 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.21
Fold 1 - Mean Absolute Error (MAE): 0.51
Fold 1 - Root Mean Squared Error (RMSE): 1.10
Fold 1 - Time taken: 6.69 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.72
Fold 2 - Mean Absolute Error (MAE): 0.51
Fold 2 - Root Mean Squared Error (RMSE): 0.85
Fold 2 - Time taken: 6.00 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.23
Fold 3 - Mean Absolute Error (MAE): 0.55
Fold 3 - Root Mean Squared Error (RMSE): 1.11
Fold 3 - Time taken: 6.00 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.70
Fold 4 - Mean Absolute Error (MAE): 0.50
Fold 4 - Root Mean Squared Error (RMSE): 0.84
Fold 4 - Time taken: 6.05 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.25
Fold 5 - Mean Absolute Error (MAE): 0.53
Fold 5 - Root Mean Squared Error (RMSE): 1.12
Fold 5 - Time taken: 4.79 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.02
Mean - Mean Absolute Error (MAE): 0.52
Mean - Root Mean Squared Error (RMSE): 1.00
Mean - Time taken: 5.91 seconds
Results saved to results.xlsx file