# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Smoothed path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 8

In [13]:
raw_data = pd.concat([sensors_data.iloc[:,:8], position_data], axis=1)
raw_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,Pos X,Pos Y,Pos Z
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,-45.581275,30.239368,-60.00
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,-45.188830,30.181623,-59.96
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,-44.791865,30.131806,-59.92
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,-44.390422,30.089935,-59.88
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,-43.984540,30.056029,-59.84
...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,-59.939858,51.788725,37.52
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,-59.963718,51.389997,37.56
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,-59.981583,50.990713,37.60
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,-59.993448,50.591032,37.64
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,-59.999315,50.191116,37.68

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
233,137.881517,153.165243,115.871574,137.406585,112.526032,135.466550,71.723841,110.006074,136.787768,148.064769,...,66.017527,85.496544,120.899409,142.309886,92.561021,120.028485,110.535489,134.283266,69.691319,107.978085
433,121.592208,139.058026,86.335605,112.792428,130.389895,146.267373,99.826221,119.987946,119.634796,130.704687,...,94.584263,103.701592,114.821028,133.999763,70.894511,103.338968,119.188531,136.770470,80.173685,108.820874
1430,145.771325,144.778557,117.656261,118.072187,126.463228,129.171448,86.779440,90.997365,140.201692,140.003560,...,70.534530,72.403997,132.179260,134.789874,97.080373,99.628982,122.543705,125.658668,84.348983,84.653341
307,127.945292,147.421209,113.727319,135.577414,104.027441,126.791389,81.781185,113.726384,127.379462,140.019466,...,76.606800,93.187422,112.670539,133.626840,94.243620,118.776527,100.195145,126.064765,76.141321,108.324982
2197,140.479449,130.043474,130.979969,115.610718,122.947593,107.437010,107.938768,88.593358,134.119687,126.435584,...,86.151970,77.977558,128.403999,114.201804,113.195831,95.589572,118.116946,103.764831,102.943053,83.082239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,131.484235,128.208485,110.374820,108.586940,125.997951,121.476007,103.909611,99.945705,125.277444,123.634429,...,87.653681,86.493576,121.246788,117.152298,96.148435,90.989753,115.804488,114.697407,93.329829,89.521456
1095,127.067786,131.636548,87.134422,99.243018,140.639940,147.382136,111.281736,118.231354,122.493099,125.273887,...,101.760375,106.238368,120.530123,126.555193,79.594324,92.938511,128.417926,134.049607,91.284220,101.472427
1130,123.972924,130.783089,84.240653,97.925160,144.913317,150.133795,114.828089,121.051632,119.591640,122.401914,...,107.283387,110.861847,123.100926,129.317637,80.236525,92.071230,128.530139,135.910449,97.377663,104.276325
1294,117.190655,120.592002,96.872234,101.981039,129.046835,133.089505,113.339273,117.095254,111.655741,113.163124,...,104.802458,106.182501,110.929615,114.110396,88.953359,95.361876,116.105467,117.990819,97.524751,102.491711
860,139.956869,150.417225,118.141071,130.418639,114.598147,127.566352,81.158577,98.930350,137.830975,141.822428,...,68.627831,78.371937,124.802738,135.087405,96.613522,111.452997,113.833996,126.712584,76.422883,97.591363

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9992972371252359
Mean Squared Error: 0.33734040693871475
Root Mean Squared Error: 0.5801380415042577
R2 Score: 0.9992972371252359
Mean Absolute Error: 0.4686771710471673
Median Absolute Error: 0.40801188598763477
Explained Variance Score: 0.9992973685085328
Time taken: 0.05463242530822754
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.9957672583752478
Mean Squared Error: 2.172013147400308
Root Mean Squared Error: 1.4624164843061596
R2 Score: 0.9957672583752478
Mean Absolute Error: 0.5652757581076365
Median Absolute Error: 0.32127693855080136
Explained Variance Score: 0.9957719457357684
Time taken: 0.04023027420043945
====================================================================================================
RandomForestRegressor
Accuracy: 0.9996776444652778
Mean Squared Error: 0.14876858288656344
Root Mean Squared Error: 0.3840142144317073
R2 Score: 0.9996776444652778
Mean Absolute Error: 0.2126919182644699
Median Absolute Error: 0.11083689902761525
Explained Variance Score: 0.9996786793599398
Time taken: 2.542436122894287
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9998342041184983
Mean Squared Error: 0.06155014152066099
Root Mean Squared Error: 0.21454675449108337
R2 Score: 0.9998342041184983
Mean Absolute Error: 0.14558631214838702
Median Absolute Error: 0.11903881661061355
Explained Variance Score: 0.9998354177144461
Time taken: 0.11621880531311035
====================================================================================================
XGBRegressor
Accuracy: 0.9981123033722358
Mean Squared Error: 0.682073023719172
Root Mean Squared Error: 0.8033056943936056
R2 Score: 0.9981123033722358
Mean Absolute Error: 0.487675157101779
Median Absolute Error: 0.28670911725070053
Explained Variance Score: 0.9981127703623568
Time taken: 0.5244808197021484
====================================================================================================