# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_scattered_48_frontback_200_iReg2.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,107.079306,130.163857,73.095839,122.852795,127.592573,140.904081,112.102986,141.330790,98.040339,102.283407,...,109.480216,108.974356,100.024180,85.504546,127.177407,119.745904,93.083083,125.740124,66.459882,114.395572
1,101.937522,121.945261,63.780240,117.817287,136.439052,144.308956,103.465533,137.934404,107.213526,103.080016,...,104.167750,101.091159,105.819773,89.132414,120.625010,108.593989,102.387146,119.931394,70.049785,112.337827
2,113.141352,114.489454,69.781323,122.498466,127.139199,140.205399,106.278360,131.667198,104.897764,105.722702,...,99.372857,95.452005,103.074718,85.189036,125.168671,113.021932,105.041424,118.311376,61.050873,118.251819
3,99.947233,125.398280,71.263070,119.147464,120.514585,136.556852,104.577318,139.282466,99.122409,110.159591,...,105.812627,102.923535,111.398340,87.816253,129.602393,115.086436,97.234629,115.032905,66.963827,123.899459
4,99.556820,124.450763,66.543331,124.424257,123.196041,152.097790,111.920567,141.763292,105.130610,104.460561,...,109.670078,103.862336,103.778824,82.784818,131.211254,114.515800,106.128121,118.338119,64.727435,112.249262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,126.892491,93.191247,101.049747,82.010963,147.608245,119.713823,127.832253,119.930239,113.245475,82.485022,...,108.365812,114.016670,106.189046,76.499513,134.480393,110.045336,131.690330,93.704385,108.927350,75.345155
2439,130.205402,97.754260,109.206235,74.459803,154.527702,132.299423,135.830468,113.752965,113.427121,89.544647,...,98.154012,111.524782,109.478128,71.834644,142.159710,112.497209,129.245599,93.990672,102.972429,87.632843
2440,125.509958,90.266258,111.683792,76.607769,154.805388,131.791833,129.799533,121.316717,114.355317,88.542155,...,104.313496,116.881478,112.726663,70.089422,137.231843,120.840177,138.101001,99.742488,106.658893,90.146370
2441,127.126851,90.521902,96.925452,84.905109,156.566845,126.704305,128.030691,115.872802,111.650199,88.145041,...,101.645145,122.680934,113.036280,67.384949,131.660830,114.714577,135.515830,99.672204,101.992923,85.516256
2442,131.081375,95.290405,104.088536,76.562931,156.785369,126.841120,128.718725,118.557258,117.912468,86.671012,...,106.314246,120.372306,108.225012,76.742345,140.027954,110.902195,131.525051,96.218247,99.256522,81.696804

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,107.079306,130.163857,73.095839,122.852795,127.592573,140.904081,112.102986,141.330790,98.040339,102.283407,...,109.480216,108.974356,100.024180,85.504546,127.177407,119.745904,93.083083,125.740124,66.459882,114.395572
1,101.937522,121.945261,63.780240,117.817287,136.439052,144.308956,103.465533,137.934404,107.213526,103.080016,...,104.167750,101.091159,105.819773,89.132414,120.625010,108.593989,102.387146,119.931394,70.049785,112.337827
2,113.141352,114.489454,69.781323,122.498466,127.139199,140.205399,106.278360,131.667198,104.897764,105.722702,...,99.372857,95.452005,103.074718,85.189036,125.168671,113.021932,105.041424,118.311376,61.050873,118.251819
3,99.947233,125.398280,71.263070,119.147464,120.514585,136.556852,104.577318,139.282466,99.122409,110.159591,...,105.812627,102.923535,111.398340,87.816253,129.602393,115.086436,97.234629,115.032905,66.963827,123.899459
4,99.556820,124.450763,66.543331,124.424257,123.196041,152.097790,111.920567,141.763292,105.130610,104.460561,...,109.670078,103.862336,103.778824,82.784818,131.211254,114.515800,106.128121,118.338119,64.727435,112.249262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,126.892491,93.191247,101.049747,82.010963,147.608245,119.713823,127.832253,119.930239,113.245475,82.485022,...,108.365812,114.016670,106.189046,76.499513,134.480393,110.045336,131.690330,93.704385,108.927350,75.345155
2439,130.205402,97.754260,109.206235,74.459803,154.527702,132.299423,135.830468,113.752965,113.427121,89.544647,...,98.154012,111.524782,109.478128,71.834644,142.159710,112.497209,129.245599,93.990672,102.972429,87.632843
2440,125.509958,90.266258,111.683792,76.607769,154.805388,131.791833,129.799533,121.316717,114.355317,88.542155,...,104.313496,116.881478,112.726663,70.089422,137.231843,120.840177,138.101001,99.742488,106.658893,90.146370
2441,127.126851,90.521902,96.925452,84.905109,156.566845,126.704305,128.030691,115.872802,111.650199,88.145041,...,101.645145,122.680934,113.036280,67.384949,131.660830,114.714577,135.515830,99.672204,101.992923,85.516256
2442,131.081375,95.290405,104.088536,76.562931,156.785369,126.841120,128.718725,118.557258,117.912468,86.671012,...,106.314246,120.372306,108.225012,76.742345,140.027954,110.902195,131.525051,96.218247,99.256522,81.696804

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.79
Fold 1 - Mean Absolute Error (MAE): 2.35
Fold 1 - Root Mean Squared Error (RMSE): 2.97
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 9.00
Fold 2 - Mean Absolute Error (MAE): 2.41
Fold 2 - Root Mean Squared Error (RMSE): 3.00
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.50
Fold 3 - Mean Absolute Error (MAE): 2.33
Fold 3 - Root Mean Squared Error (RMSE): 2.92
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 9.20
Fold 4 - Mean Absolute Error (MAE): 2.43
Fold 4 - Root Mean Squared Error (RMSE): 3.03
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 8.34
Fold 5 - Mean Absolute Error (MAE): 2.31
Fold 5 - Root Mean Squared Error (RMSE): 2.89
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 8.77
Mean - Mean Absolute Error (MAE): 2.36
Mean - Root Mean Squared Error (RMSE): 2.96
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 81.53
Fold 1 - Mean Absolute Error (MAE): 5.73
Fold 1 - Root Mean Squared Error (RMSE): 9.03
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 85.11
Fold 2 - Mean Absolute Error (MAE): 5.74
Fold 2 - Root Mean Squared Error (RMSE): 9.23
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 87.65
Fold 3 - Mean Absolute Error (MAE): 5.84
Fold 3 - Root Mean Squared Error (RMSE): 9.36
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 97.18
Fold 4 - Mean Absolute Error (MAE): 6.41
Fold 4 - Root Mean Squared Error (RMSE): 9.86
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 85.14
Fold 5 - Mean Absolute Error (MAE): 5.87
Fold 5 - Root Mean Squared Error (RMSE): 9.23
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 87.32
Mean - Mean Absolute Error (MAE): 5.92
Mean - Root Mean Squared Error (RMSE): 9.34
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 17.39
Fold 1 - Mean Absolute Error (MAE): 3.32
Fold 1 - Root Mean Squared Error (RMSE): 4.17
Fold 1 - Time taken: 2.49 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 17.93
Fold 2 - Mean Absolute Error (MAE): 3.36
Fold 2 - Root Mean Squared Error (RMSE): 4.23
Fold 2 - Time taken: 2.55 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 17.10
Fold 3 - Mean Absolute Error (MAE): 3.33
Fold 3 - Root Mean Squared Error (RMSE): 4.14
Fold 3 - Time taken: 3.83 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 17.31
Fold 4 - Mean Absolute Error (MAE): 3.31
Fold 4 - Root Mean Squared Error (RMSE): 4.16
Fold 4 - Time taken: 3.88 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 17.89
Fold 5 - Mean Absolute Error (MAE): 3.31
Fold 5 - Root Mean Squared Error (RMSE): 4.23
Fold 5 - Time taken: 3.89 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 17.52
Mean - Mean Absolute Error (MAE): 3.32
Mean - Root Mean Squared Error (RMSE): 4.19
Mean - Time taken: 3.33 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.45
Fold 1 - Mean Absolute Error (MAE): 1.53
Fold 1 - Root Mean Squared Error (RMSE): 2.33
Fold 1 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.22
Fold 2 - Mean Absolute Error (MAE): 1.50
Fold 2 - Root Mean Squared Error (RMSE): 2.29
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.60
Fold 3 - Mean Absolute Error (MAE): 1.55
Fold 3 - Root Mean Squared Error (RMSE): 2.37
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 5.20
Fold 4 - Mean Absolute Error (MAE): 1.51
Fold 4 - Root Mean Squared Error (RMSE): 2.28
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 5.56
Fold 5 - Mean Absolute Error (MAE): 1.54
Fold 5 - Root Mean Squared Error (RMSE): 2.36
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.41
Mean - Mean Absolute Error (MAE): 1.52
Mean - Root Mean Squared Error (RMSE): 2.32
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 18.05
Fold 1 - Mean Absolute Error (MAE): 3.10
Fold 1 - Root Mean Squared Error (RMSE): 4.25
Fold 1 - Time taken: 1.96 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 20.22
Fold 2 - Mean Absolute Error (MAE): 3.30
Fold 2 - Root Mean Squared Error (RMSE): 4.50
Fold 2 - Time taken: 1.94 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 19.83
Fold 3 - Mean Absolute Error (MAE): 3.31
Fold 3 - Root Mean Squared Error (RMSE): 4.45
Fold 3 - Time taken: 1.94 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 20.81
Fold 4 - Mean Absolute Error (MAE): 3.33
Fold 4 - Root Mean Squared Error (RMSE): 4.56
Fold 4 - Time taken: 1.97 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 16.51
Fold 5 - Mean Absolute Error (MAE): 3.07
Fold 5 - Root Mean Squared Error (RMSE): 4.06
Fold 5 - Time taken: 1.96 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 19.08
Mean - Mean Absolute Error (MAE): 3.22
Mean - Root Mean Squared Error (RMSE): 4.36
Mean - Time taken: 1.95 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_scattered_48_frontback_200_iReg2.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_scattered_48_frontback_200_iReg2.xlsx file")

Results saved to Results__PL_scattered_48_frontback_200_iReg2.xlsx file