# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Smoothed path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 24

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:24]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,sensor22,sensor23,sensor24
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,108.602786,127.546015,100.671285,128.838731,75.131774,114.983863,115.781632,140.681499,100.697724,129.781474
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,108.602786,127.546015,100.671285,128.838731,75.131774,114.983863,115.781632,140.681499,100.697724,129.781474
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,108.602786,127.546015,100.671285,128.838731,75.131774,114.983863,115.781632,140.681499,100.697724,129.781474
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,108.602786,127.546015,100.671285,128.838731,75.131774,114.983863,115.781632,140.681499,100.697724,129.781474
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,108.602786,127.546015,100.671285,128.838731,75.131774,114.983863,115.781632,140.681499,100.697724,129.781474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,125.037299,112.888952,130.048906,112.926596,100.690746,73.099536,144.734446,131.071435,123.635019,105.756975
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,125.037299,112.888952,130.048906,112.926596,100.690746,73.099536,144.734446,131.071435,123.635019,105.756975
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,125.037299,112.888952,130.048906,112.926596,100.690746,73.099536,144.734446,131.071435,123.635019,105.756975
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,125.037299,112.888952,130.048906,112.926596,100.690746,73.099536,144.734446,131.071435,123.635019,105.756975
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,125.037299,112.888952,130.048906,112.926596,100.690746,73.099536,144.734446,131.071435,123.635019,105.756975

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21,sensor22,sensor23,sensor24
233,137.881517,153.165243,115.871574,137.406585,112.526032,135.466550,71.723841,110.006074,136.787768,148.064769,...,67.307544,97.115230,129.551755,149.919020,102.683513,128.154302,110.905385,133.364214,69.304850,108.862294
433,121.592208,139.058026,86.335605,112.792428,130.389895,146.267373,99.826221,119.987946,119.634796,130.704687,...,97.363297,112.775014,117.639998,135.128012,76.841315,107.130121,123.038745,139.381611,86.616492,112.839707
1430,145.771325,144.778557,117.656261,118.072187,126.463228,129.171448,86.779440,90.997365,140.201692,140.003560,...,79.892326,83.009180,138.320985,138.913905,105.730530,108.250602,125.585998,125.913066,84.863571,86.550922
307,127.945292,147.421209,113.727319,135.577414,104.027441,126.791389,81.781185,113.726384,127.379462,140.019466,...,77.426983,103.663742,120.129227,138.543822,103.122863,129.008224,102.530736,124.819441,78.954083,110.928583
2197,140.479449,130.043474,130.979969,115.610718,122.947593,107.437010,107.938768,88.593358,134.119687,126.435584,...,96.142969,81.773537,132.243650,121.948850,120.710479,104.788589,119.127386,104.967444,104.427958,83.678985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,131.484235,128.208485,110.374820,108.586940,125.997951,121.476007,103.909611,99.945705,125.277444,123.634429,...,96.760435,93.895482,124.969317,122.332517,103.162358,98.329501,120.380874,119.524276,95.500772,94.558253
1095,127.067786,131.636548,87.134422,99.243018,140.639940,147.382136,111.281736,118.231354,122.493099,125.273887,...,104.200710,109.011718,121.824453,129.051574,79.363973,92.896423,132.872459,139.666528,101.655257,109.060746
1130,123.972924,130.783089,84.240653,97.925160,144.913317,150.133795,114.828089,121.051632,119.591640,122.401914,...,109.998003,114.380211,121.509663,127.473642,80.679961,90.843572,136.648762,143.095836,103.740616,111.805489
1294,117.190655,120.592002,96.872234,101.981039,129.046835,133.089505,113.339273,117.095254,111.655741,113.163124,...,108.738702,110.944512,112.887730,116.649741,92.539130,96.316638,121.129664,124.278463,103.817703,109.501359
860,139.956869,150.417225,118.141071,130.418639,114.598147,127.566352,81.158577,98.930350,137.830975,141.822428,...,73.759383,88.432945,131.623372,143.479287,105.638767,121.588820,114.082338,127.855230,76.764466,97.500142

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9987228042969397
Mean Squared Error: 0.5936964284243721
Root Mean Squared Error: 0.7701727805711172
R2 Score: 0.9987228042969397
Mean Absolute Error: 0.6154927661053341
Median Absolute Error: 0.5386645799598782
Explained Variance Score: 0.9987246645498192
Time taken: 0.004499673843383789
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.9968404434928092
Mean Squared Error: 1.7041830038717987
Root Mean Squared Error: 1.288721103374811
R2 Score: 0.9968404434928092
Mean Absolute Error: 0.5215203052900015
Median Absolute Error: 0.3210484364492044
Explained Variance Score: 0.9968435643170226
Time taken: 0.0214998722076416
====================================================================================================
RandomForestRegressor
Accuracy: 0.9994490555307619
Mean Squared Error: 0.2704140572600202
Root Mean Squared Error: 0.51375369980921
R2 Score: 0.9994490555307619
Mean Absolute Error: 0.24531110196240502
Median Absolute Error: 0.13276763624610055
Explained Variance Score: 0.9994502283147689
Time taken: 1.2234976291656494
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9997958265882199
Mean Squared Error: 0.07762833223373036
Root Mean Squared Error: 0.24085437576478674
R2 Score: 0.9997958265882199
Mean Absolute Error: 0.16345090736747173
Median Absolute Error: 0.13313695665569844
Explained Variance Score: 0.9997972892776285
Time taken: 0.05697464942932129
====================================================================================================
XGBRegressor
Accuracy: 0.9971909343892391
Mean Squared Error: 1.4417291499663776
Root Mean Squared Error: 1.1924216852750331
R2 Score: 0.9971909343892391
Mean Absolute Error: 0.5654379344192845
Median Absolute Error: 0.3310139281598488
Explained Variance Score: 0.997198024730798
Time taken: 0.3984982967376709
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.59
Fold 1 - Mean Absolute Error (MAE): 0.62
Fold 1 - Root Mean Squared Error (RMSE): 0.77
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.62
Fold 2 - Mean Absolute Error (MAE): 0.63
Fold 2 - Root Mean Squared Error (RMSE): 0.79
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.59
Fold 3 - Mean Absolute Error (MAE): 0.62
Fold 3 - Root Mean Squared Error (RMSE): 0.77
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.63
Fold 4 - Mean Absolute Error (MAE): 0.63
Fold 4 - Root Mean Squared Error (RMSE): 0.79
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.61
Fold 5 - Mean Absolute Error (MAE): 0.63
Fold 5 - Root Mean Squared Error (RMSE): 0.78
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 0.61
Mean MAE: 0.62
Mean RMSE: 0.78
Mean time: 0.01 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.35
Fold 1 - Mean Absolute Error (MAE): 0.53
Fold 1 - Root Mean Squared Error (RMSE): 1.16
Fold 1 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.39
Fold 2 - Mean Absolute Error (MAE): 0.49
Fold 2 - Root Mean Squared Error (RMSE): 1.18
Fold 2 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 3.51
Fold 3 - Mean Absolute Error (MAE): 0.57
Fold 3 - Root Mean Squared Error (RMSE): 1.87
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.67
Fold 4 - Mean Absolute Error (MAE): 0.48
Fold 4 - Root Mean Squared Error (RMSE): 0.82
Fold 4 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 0.56
Fold 5 - Mean Absolute Error (MAE): 0.44
Fold 5 - Root Mean Squared Error (RMSE): 0.75
Fold 5 - Time taken: 0.02 seconds
Mean MSE: 1.50
Mean MAE: 0.50
Mean RMSE: 1.16
Mean time: 0.02 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.25
Fold 1 - Mean Absolute Error (MAE): 0.24
Fold 1 - Root Mean Squared Error (RMSE): 0.50
Fold 1 - Time taken: 1.21 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.33
Fold 2 - Mean Absolute Error (MAE): 0.24
Fold 2 - Root Mean Squared Error (RMSE): 0.58
Fold 2 - Time taken: 1.22 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.28
Fold 3 - Mean Absolute Error (MAE): 0.25
Fold 3 - Root Mean Squared Error (RMSE): 0.53
Fold 3 - Time taken: 1.55 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.12
Fold 4 - Mean Absolute Error (MAE): 0.20
Fold 4 - Root Mean Squared Error (RMSE): 0.35
Fold 4 - Time taken: 2.13 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.15
Fold 5 - Mean Absolute Error (MAE): 0.21
Fold 5 - Root Mean Squared Error (RMSE): 0.39
Fold 5 - Time taken: 2.10 seconds
Mean MSE: 0.23
Mean MAE: 0.23
Mean RMSE: 0.47
Mean time: 1.64 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.06
Fold 1 - Mean Absolute Error (MAE): 0.16
Fold 1 - Root Mean Squared Error (RMSE): 0.25
Fold 1 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.09
Fold 2 - Mean Absolute Error (MAE): 0.17
Fold 2 - Root Mean Squared Error (RMSE): 0.29
Fold 2 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.10
Fold 3 - Mean Absolute Error (MAE): 0.18
Fold 3 - Root Mean Squared Error (RMSE): 0.31
Fold 3 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.08
Fold 4 - Mean Absolute Error (MAE): 0.18
Fold 4 - Root Mean Squared Error (RMSE): 0.29
Fold 4 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.08
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.29
Fold 5 - Time taken: 0.07 seconds
Mean MSE: 0.08
Mean MAE: 0.17
Mean RMSE: 0.29
Mean time: 0.07 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.44
Fold 1 - Mean Absolute Error (MAE): 0.57
Fold 1 - Root Mean Squared Error (RMSE): 1.20
Fold 1 - Time taken: 6.25 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.87
Fold 2 - Mean Absolute Error (MAE): 0.55
Fold 2 - Root Mean Squared Error (RMSE): 0.93
Fold 2 - Time taken: 6.07 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.18
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 1.09
Fold 3 - Time taken: 6.09 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.78
Fold 4 - Mean Absolute Error (MAE): 0.51
Fold 4 - Root Mean Squared Error (RMSE): 0.88
Fold 4 - Time taken: 6.11 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.50
Fold 5 - Mean Absolute Error (MAE): 0.57
Fold 5 - Root Mean Squared Error (RMSE): 1.22
Fold 5 - Time taken: 14.29 seconds
Mean MSE: 1.15
Mean MAE: 0.55
Mean RMSE: 1.06
Mean time: 7.76 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Smoothed path loss - (1-24) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.59
Fold 1 - Mean Absolute Error (MAE): 0.62
Fold 1 - Root Mean Squared Error (RMSE): 0.77
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.62
Fold 2 - Mean Absolute Error (MAE): 0.63
Fold 2 - Root Mean Squared Error (RMSE): 0.79
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.59
Fold 3 - Mean Absolute Error (MAE): 0.62
Fold 3 - Root Mean Squared Error (RMSE): 0.77
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.63
Fold 4 - Mean Absolute Error (MAE): 0.63
Fold 4 - Root Mean Squared Error (RMSE): 0.79
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.61
Fold 5 - Mean Absolute Error (MAE): 0.63
Fold 5 - Root Mean Squared Error (RMSE): 0.78
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.61
Mean - Mean Absolute Error (MAE): 0.62
Mean - Root Mean Squared Error (RMSE): 0.78
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 1.22
Fold 1 - Mean Absolute Error (MAE): 0.48
Fold 1 - Root Mean Squared Error (RMSE): 1.10
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.13
Fold 2 - Mean Absolute Error (MAE): 0.51
Fold 2 - Root Mean Squared Error (RMSE): 1.06
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 1.72
Fold 3 - Mean Absolute Error (MAE): 0.52
Fold 3 - Root Mean Squared Error (RMSE): 1.31
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 0.46
Fold 4 - Mean Absolute Error (MAE): 0.42
Fold 4 - Root Mean Squared Error (RMSE): 0.68
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.19
Fold 5 - Mean Absolute Error (MAE): 0.51
Fold 5 - Root Mean Squared Error (RMSE): 1.09
Fold 5 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 1.14
Mean - Mean Absolute Error (MAE): 0.49
Mean - Root Mean Squared Error (RMSE): 1.05
Mean - Time taken: 0.04 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.29
Fold 1 - Mean Absolute Error (MAE): 0.25
Fold 1 - Root Mean Squared Error (RMSE): 0.54
Fold 1 - Time taken: 2.09 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.37
Fold 2 - Mean Absolute Error (MAE): 0.25
Fold 2 - Root Mean Squared Error (RMSE): 0.61
Fold 2 - Time taken: 2.10 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.33
Fold 3 - Mean Absolute Error (MAE): 0.27
Fold 3 - Root Mean Squared Error (RMSE): 0.58
Fold 3 - Time taken: 2.09 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.15
Fold 4 - Mean Absolute Error (MAE): 0.21
Fold 4 - Root Mean Squared Error (RMSE): 0.39
Fold 4 - Time taken: 2.10 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.16
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.40
Fold 5 - Time taken: 2.08 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.26
Mean - Mean Absolute Error (MAE): 0.24
Mean - Root Mean Squared Error (RMSE): 0.50
Mean - Time taken: 2.09 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.06
Fold 1 - Mean Absolute Error (MAE): 0.16
Fold 1 - Root Mean Squared Error (RMSE): 0.25
Fold 1 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.09
Fold 2 - Mean Absolute Error (MAE): 0.17
Fold 2 - Root Mean Squared Error (RMSE): 0.29
Fold 2 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.10
Fold 3 - Mean Absolute Error (MAE): 0.18
Fold 3 - Root Mean Squared Error (RMSE): 0.31
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.08
Fold 4 - Mean Absolute Error (MAE): 0.18
Fold 4 - Root Mean Squared Error (RMSE): 0.29
Fold 4 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.08
Fold 5 - Mean Absolute Error (MAE): 0.17
Fold 5 - Root Mean Squared Error (RMSE): 0.29
Fold 5 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.08
Mean - Mean Absolute Error (MAE): 0.17
Mean - Root Mean Squared Error (RMSE): 0.29
Mean - Time taken: 0.07 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 1.44
Fold 1 - Mean Absolute Error (MAE): 0.57
Fold 1 - Root Mean Squared Error (RMSE): 1.20
Fold 1 - Time taken: 5.90 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 0.87
Fold 2 - Mean Absolute Error (MAE): 0.55
Fold 2 - Root Mean Squared Error (RMSE): 0.93
Fold 2 - Time taken: 5.88 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.18
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 1.09
Fold 3 - Time taken: 6.11 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 0.78
Fold 4 - Mean Absolute Error (MAE): 0.51
Fold 4 - Root Mean Squared Error (RMSE): 0.88
Fold 4 - Time taken: 5.47 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.50
Fold 5 - Mean Absolute Error (MAE): 0.57
Fold 5 - Root Mean Squared Error (RMSE): 1.22
Fold 5 - Time taken: 2.09 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.15
Mean - Mean Absolute Error (MAE): 0.55
Mean - Root Mean Squared Error (RMSE): 1.06
Mean - Time taken: 5.09 seconds
Results saved to results.xlsx file