# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Scattered path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 40

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:40]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor31,sensor32,sensor33,sensor34,sensor35,sensor36,sensor37,sensor38,sensor39,sensor40
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,108.047877,140.244547,109.565729,109.070545,82.893900,98.589125,127.512697,129.486254,109.733925,122.659778
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,112.790714,128.411134,100.484057,111.452682,73.125233,101.282473,125.960497,134.441514,113.915353,123.190051
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,106.249265,130.156309,96.502953,118.956893,79.333567,97.267900,133.077599,139.007648,112.052375,117.562515
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,103.720363,132.493487,98.302056,116.580605,87.824924,94.036434,126.398457,132.107357,108.861984,129.042510
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,105.749524,128.893260,104.693657,115.118536,81.096908,93.196633,123.182719,128.847588,108.706859,119.970422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,123.473334,110.321790,108.457671,107.981938,85.180655,73.015884,147.381832,135.026131,119.309378,112.129281
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,132.120534,110.618646,117.294786,106.740114,85.424751,68.648789,136.726601,132.596080,119.776043,109.341785
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,135.492966,109.283794,116.787148,102.425103,86.943908,73.622470,141.008696,136.607714,124.257271,108.008908
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,132.120728,100.956413,118.196210,110.783778,81.725527,68.838207,140.712648,140.075617,125.544587,114.946916
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,129.010136,106.652696,110.312460,103.197607,83.834217,69.625782,150.800243,131.837953,120.001152,109.766753

# MinMaxScaler

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler = MinMaxScaler()
sensors_data = scaler.fit_transform(sensors_data)

# Split the data into training and testing sets

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [17]:
X_train

array([[0.64939895, 0.71374411, 0.63715848, ..., 0.44181828, 0.1531416 ,
        0.40922817],
       [0.371659  , 0.62388101, 0.26637783, ..., 0.77945532, 0.57334929,
        0.50046485],
       [0.80223265, 0.70958588, 0.71892324, ..., 0.46195365, 0.32449216,
        0.26789362],
       ...,
       [0.37878048, 0.40050675, 0.27373019, ..., 0.81713955, 0.70701553,
        0.66020439],
       [0.41226104, 0.38637897, 0.53501141, ..., 0.60398159, 0.76764623,
        0.55945589],
       [0.73349867, 0.63770894, 0.6686133 , ..., 0.34264436, 0.2697041 ,
        0.200839  ]])

In [18]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [20]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [21]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9796327073326473
Mean Squared Error: 8.982501574667326
Root Mean Squared Error: 2.9945943520759877
R2 Score: 0.9796327073326473
Mean Absolute Error: 2.3947785246419993
Median Absolute Error: 1.9816366177918223
Explained Variance Score: 0.9796520584718859
Time taken: 0.004499912261962891
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.7802821066212599
Mean Squared Error: 106.25801835170621
Root Mean Squared Error: 10.27556699918498
R2 Score: 0.7802821066212599
Mean Absolute Error: 6.598969767034252
Median Absolute Error: 3.4179797605414337
Explained Variance Score: 0.7818996162508717
Time taken: 0.03749895095825195
====================================================================================================
RandomForestRegressor
Accuracy: 0.958867038932035
Mean Squared Error: 19.236875645750917
Root Mean Squared Error: 4.382826081479799
R2 Score: 0.958867038932035
Mean Absolute Error: 3.476764111230525
Median Absolute Error: 2.912685346507038
Explained Variance Score: 0.959197378465285
Time taken: 2.176496744155884
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9876686477183108
Mean Squared Error: 5.956919015897131
Root Mean Squared Error: 2.2972307561682537
R2 Score: 0.9876686477183108
Mean Absolute Error: 1.5977602286679975
Median Absolute Error: 1.1351064710545355
Explained Variance Score: 0.9876903971767653
Time taken: 0.052500247955322266
====================================================================================================
XGBRegressor
Accuracy: 0.9601304403628221
Mean Squared Error: 20.44830748742154
Root Mean Squared Error: 4.504017458110024
R2 Score: 0.9601304403628221
Mean Absolute Error: 3.316167856094045
Median Absolute Error: 2.3515920192643898
Explained Variance Score: 0.9603161974185944
Time taken: 0.559497594833374
====================================================================================================

# Cross Validation

In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.98
Fold 1 - Mean Absolute Error (MAE): 2.39
Fold 1 - Root Mean Squared Error (RMSE): 3.00
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 9.36
Fold 2 - Mean Absolute Error (MAE): 2.43
Fold 2 - Root Mean Squared Error (RMSE): 3.06
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.96
Fold 3 - Mean Absolute Error (MAE): 2.39
Fold 3 - Root Mean Squared Error (RMSE): 2.99
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 9.32
Fold 4 - Mean Absolute Error (MAE): 2.44
Fold 4 - Root Mean Squared Error (RMSE): 3.05
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 9.43
Fold 5 - Mean Absolute Error (MAE): 2.44
Fold 5 - Root Mean Squared Error (RMSE): 3.07
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 9.21
Mean MAE: 2.42
Mean RMSE: 3.04
Mean time: 0.01 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 91.00
Fold 1 - Mean Absolute Error (MAE): 6.04
Fold 1 - Root Mean Squared Error (RMSE): 9.54
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 89.31
Fold 2 - Mean Absolute Error (MAE): 5.89
Fold 2 - Root Mean Squared Error (RMSE): 9.45
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 84.92
Fold 3 - Mean Absolute Error (MAE): 5.79
Fold 3 - Root Mean Squared Error (RMSE): 9.21
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 102.08
Fold 4 - Mean Absolute Error (MAE): 6.48
Fold 4 - Root Mean Squared Error (RMSE): 10.10
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 99.53
Fold 5 - Mean Absolute Error (MAE): 6.28
Fold 5 - Root Mean Squared Error (RMSE): 9.98
Fold 5 - Time taken: 0.04 seconds
Mean MSE: 93.37
Mean MAE: 6.10
Mean RMSE: 9.66
Mean time: 0.04 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 18.46
Fold 1 - Mean Absolute Error (MAE): 3.43
Fold 1 - Root Mean Squared Error (RMSE): 4.30
Fold 1 - Time taken: 2.43 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 16.41
Fold 2 - Mean Absolute Error (MAE): 3.26
Fold 2 - Root Mean Squared Error (RMSE): 4.05
Fold 2 - Time taken: 3.64 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 17.90
Fold 3 - Mean Absolute Error (MAE): 3.41
Fold 3 - Root Mean Squared Error (RMSE): 4.23
Fold 3 - Time taken: 3.64 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 18.83
Fold 4 - Mean Absolute Error (MAE): 3.48
Fold 4 - Root Mean Squared Error (RMSE): 4.34
Fold 4 - Time taken: 4.33 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 18.19
Fold 5 - Mean Absolute Error (MAE): 3.38
Fold 5 - Root Mean Squared Error (RMSE): 4.26
Fold 5 - Time taken: 3.73 seconds
Mean MSE: 17.96
Mean MAE: 3.39
Mean RMSE: 4.24
Mean time: 3.55 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.96
Fold 1 - Mean Absolute Error (MAE): 1.60
Fold 1 - Root Mean Squared Error (RMSE): 2.44
Fold 1 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 6.00
Fold 2 - Mean Absolute Error (MAE): 1.61
Fold 2 - Root Mean Squared Error (RMSE): 2.45
Fold 2 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 6.24
Fold 3 - Mean Absolute Error (MAE): 1.64
Fold 3 - Root Mean Squared Error (RMSE): 2.50
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 6.49
Fold 4 - Mean Absolute Error (MAE): 1.67
Fold 4 - Root Mean Squared Error (RMSE): 2.55
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 7.04
Fold 5 - Mean Absolute Error (MAE): 1.73
Fold 5 - Root Mean Squared Error (RMSE): 2.65
Fold 5 - Time taken: 0.06 seconds
Mean MSE: 6.35
Mean MAE: 1.65
Mean RMSE: 2.52
Mean time: 0.06 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 20.45
Fold 1 - Mean Absolute Error (MAE): 3.32
Fold 1 - Root Mean Squared Error (RMSE): 4.52
Fold 1 - Time taken: 6.80 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 21.52
Fold 2 - Mean Absolute Error (MAE): 3.36
Fold 2 - Root Mean Squared Error (RMSE): 4.64
Fold 2 - Time taken: 7.28 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 20.31
Fold 3 - Mean Absolute Error (MAE): 3.33
Fold 3 - Root Mean Squared Error (RMSE): 4.51
Fold 3 - Time taken: 6.69 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 21.78
Fold 4 - Mean Absolute Error (MAE): 3.38
Fold 4 - Root Mean Squared Error (RMSE): 4.67
Fold 4 - Time taken: 6.72 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 22.19
Fold 5 - Mean Absolute Error (MAE): 3.43
Fold 5 - Root Mean Squared Error (RMSE): 4.71
Fold 5 - Time taken: 11.49 seconds
Mean MSE: 21.25
Mean MAE: 3.36
Mean RMSE: 4.61
Mean time: 7.80 seconds
--------------------------------------------------

# Excel File Conversion

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("MinMaxScaler - (1-40) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.98
Fold 1 - Mean Absolute Error (MAE): 2.39
Fold 1 - Root Mean Squared Error (RMSE): 3.00
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 9.36
Fold 2 - Mean Absolute Error (MAE): 2.43
Fold 2 - Root Mean Squared Error (RMSE): 3.06
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.96
Fold 3 - Mean Absolute Error (MAE): 2.39
Fold 3 - Root Mean Squared Error (RMSE): 2.99
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 9.32
Fold 4 - Mean Absolute Error (MAE): 2.44
Fold 4 - Root Mean Squared Error (RMSE): 3.05
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 9.43
Fold 5 - Mean Absolute Error (MAE): 2.44
Fold 5 - Root Mean Squared Error (RMSE): 3.07
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 9.21
Mean - Mean Absolute Error (MAE): 2.42
Mean - Root Mean Squared Error (RMSE): 3.04
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 107.02
Fold 1 - Mean Absolute Error (MAE): 6.63
Fold 1 - Root Mean Squared Error (RMSE): 10.35
Fold 1 - Time taken: 0.07 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 87.11
Fold 2 - Mean Absolute Error (MAE): 5.84
Fold 2 - Root Mean Squared Error (RMSE): 9.33
Fold 2 - Time taken: 0.08 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 87.18
Fold 3 - Mean Absolute Error (MAE): 5.92
Fold 3 - Root Mean Squared Error (RMSE): 9.34
Fold 3 - Time taken: 0.07 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 98.94
Fold 4 - Mean Absolute Error (MAE): 6.43
Fold 4 - Root Mean Squared Error (RMSE): 9.95
Fold 4 - Time taken: 0.07 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 98.64
Fold 5 - Mean Absolute Error (MAE): 6.15
Fold 5 - Root Mean Squared Error (RMSE): 9.93
Fold 5 - Time taken: 0.07 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 95.78
Mean - Mean Absolute Error (MAE): 6.19
Mean - Root Mean Squared Error (RMSE): 9.78
Mean - Time taken: 0.07 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 17.88
Fold 1 - Mean Absolute Error (MAE): 3.36
Fold 1 - Root Mean Squared Error (RMSE): 4.23
Fold 1 - Time taken: 3.66 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 16.40
Fold 2 - Mean Absolute Error (MAE): 3.24
Fold 2 - Root Mean Squared Error (RMSE): 4.05
Fold 2 - Time taken: 3.63 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 18.04
Fold 3 - Mean Absolute Error (MAE): 3.43
Fold 3 - Root Mean Squared Error (RMSE): 4.25
Fold 3 - Time taken: 3.61 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 19.72
Fold 4 - Mean Absolute Error (MAE): 3.56
Fold 4 - Root Mean Squared Error (RMSE): 4.44
Fold 4 - Time taken: 3.63 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 17.71
Fold 5 - Mean Absolute Error (MAE): 3.37
Fold 5 - Root Mean Squared Error (RMSE): 4.21
Fold 5 - Time taken: 3.61 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 17.95
Mean - Mean Absolute Error (MAE): 3.39
Mean - Root Mean Squared Error (RMSE): 4.24
Mean - Time taken: 3.63 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.96
Fold 1 - Mean Absolute Error (MAE): 1.60
Fold 1 - Root Mean Squared Error (RMSE): 2.44
Fold 1 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 6.00
Fold 2 - Mean Absolute Error (MAE): 1.61
Fold 2 - Root Mean Squared Error (RMSE): 2.45
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 6.24
Fold 3 - Mean Absolute Error (MAE): 1.64
Fold 3 - Root Mean Squared Error (RMSE): 2.50
Fold 3 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 6.49
Fold 4 - Mean Absolute Error (MAE): 1.67
Fold 4 - Root Mean Squared Error (RMSE): 2.55
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 7.04
Fold 5 - Mean Absolute Error (MAE): 1.73
Fold 5 - Root Mean Squared Error (RMSE): 2.65
Fold 5 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 6.35
Mean - Mean Absolute Error (MAE): 1.65
Mean - Root Mean Squared Error (RMSE): 2.52
Mean - Time taken: 0.06 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 20.45
Fold 1 - Mean Absolute Error (MAE): 3.32
Fold 1 - Root Mean Squared Error (RMSE): 4.52
Fold 1 - Time taken: 6.50 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 21.52
Fold 2 - Mean Absolute Error (MAE): 3.36
Fold 2 - Root Mean Squared Error (RMSE): 4.64
Fold 2 - Time taken: 6.48 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 20.31
Fold 3 - Mean Absolute Error (MAE): 3.33
Fold 3 - Root Mean Squared Error (RMSE): 4.51
Fold 3 - Time taken: 5.64 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 21.78
Fold 4 - Mean Absolute Error (MAE): 3.38
Fold 4 - Root Mean Squared Error (RMSE): 4.67
Fold 4 - Time taken: 3.78 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 22.19
Fold 5 - Mean Absolute Error (MAE): 3.43
Fold 5 - Root Mean Squared Error (RMSE): 4.71
Fold 5 - Time taken: 2.14 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 21.25
Mean - Mean Absolute Error (MAE): 3.36
Mean - Root Mean Squared Error (RMSE): 4.61
Mean - Time taken: 4.91 seconds
Results saved to results.xlsx file