# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_scattered_48_frontback_200_iReg1.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,98.446190,137.385115,76.517891,119.952576,109.123847,148.334493,101.750377,136.050701,95.538300,119.519323,...,103.428722,95.321557,108.223701,83.328814,127.852730,117.878216,100.005230,128.731960,82.593814,119.793564
1,96.012761,135.706183,75.559535,115.837374,120.948247,145.878636,100.621695,136.332422,96.596513,118.201936,...,104.914438,99.682038,104.247218,90.944454,139.042616,108.242219,93.393960,133.737781,78.398126,121.596396
2,97.968722,131.895154,67.614038,124.457516,104.188273,136.462004,97.916838,137.306264,94.570180,119.023850,...,99.302249,102.396566,104.963522,85.406666,121.032529,113.730889,111.130938,129.838283,72.578591,117.972105
3,105.838877,138.632647,75.686830,123.465038,110.569408,148.930196,94.930829,138.865453,90.244495,114.330196,...,100.397336,103.724611,104.016982,92.869025,123.771913,108.695023,99.539432,135.495397,78.624337,120.652453
4,102.702775,129.187193,74.256071,115.949465,111.860698,145.241046,97.252698,131.251834,100.747056,120.592625,...,108.051482,90.624637,99.257933,94.337469,121.619953,122.064400,97.953750,138.380861,78.611829,119.958941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,127.042012,117.664254,102.880592,75.733155,135.050510,137.186059,115.961727,116.012361,106.055577,111.736676,...,109.496668,113.045465,109.713120,73.858579,140.117135,106.746626,130.836539,119.530396,110.770618,85.974669
2439,124.572140,119.357959,101.080247,76.415536,136.064033,133.552153,113.292208,117.045559,115.455752,104.163960,...,114.547728,113.209642,108.207569,61.759714,135.322016,114.205762,132.824566,123.985882,103.834129,82.703497
2440,127.561770,122.792408,116.390746,83.346924,135.933177,135.221435,112.064249,112.246387,118.393113,104.482804,...,99.745880,129.381690,117.111341,74.757599,131.885241,111.454662,130.840472,120.780130,106.572034,84.414852
2441,120.913883,113.001177,101.591062,77.652338,142.119238,137.603803,119.857057,116.765483,124.629168,108.914562,...,108.920523,107.193196,108.607481,74.783473,143.830974,113.508768,128.548557,109.545396,108.594633,84.391644
2442,123.766996,113.034371,98.334357,81.224213,148.738873,142.250394,112.400529,117.805625,116.273503,108.159465,...,105.816336,120.728867,113.714433,75.632429,133.272510,107.226803,128.451701,122.512200,96.992274,80.871394

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,98.446190,137.385115,76.517891,119.952576,109.123847,148.334493,101.750377,136.050701,95.538300,119.519323,...,103.428722,95.321557,108.223701,83.328814,127.852730,117.878216,100.005230,128.731960,82.593814,119.793564
1,96.012761,135.706183,75.559535,115.837374,120.948247,145.878636,100.621695,136.332422,96.596513,118.201936,...,104.914438,99.682038,104.247218,90.944454,139.042616,108.242219,93.393960,133.737781,78.398126,121.596396
2,97.968722,131.895154,67.614038,124.457516,104.188273,136.462004,97.916838,137.306264,94.570180,119.023850,...,99.302249,102.396566,104.963522,85.406666,121.032529,113.730889,111.130938,129.838283,72.578591,117.972105
3,105.838877,138.632647,75.686830,123.465038,110.569408,148.930196,94.930829,138.865453,90.244495,114.330196,...,100.397336,103.724611,104.016982,92.869025,123.771913,108.695023,99.539432,135.495397,78.624337,120.652453
4,102.702775,129.187193,74.256071,115.949465,111.860698,145.241046,97.252698,131.251834,100.747056,120.592625,...,108.051482,90.624637,99.257933,94.337469,121.619953,122.064400,97.953750,138.380861,78.611829,119.958941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,127.042012,117.664254,102.880592,75.733155,135.050510,137.186059,115.961727,116.012361,106.055577,111.736676,...,109.496668,113.045465,109.713120,73.858579,140.117135,106.746626,130.836539,119.530396,110.770618,85.974669
2439,124.572140,119.357959,101.080247,76.415536,136.064033,133.552153,113.292208,117.045559,115.455752,104.163960,...,114.547728,113.209642,108.207569,61.759714,135.322016,114.205762,132.824566,123.985882,103.834129,82.703497
2440,127.561770,122.792408,116.390746,83.346924,135.933177,135.221435,112.064249,112.246387,118.393113,104.482804,...,99.745880,129.381690,117.111341,74.757599,131.885241,111.454662,130.840472,120.780130,106.572034,84.414852
2441,120.913883,113.001177,101.591062,77.652338,142.119238,137.603803,119.857057,116.765483,124.629168,108.914562,...,108.920523,107.193196,108.607481,74.783473,143.830974,113.508768,128.548557,109.545396,108.594633,84.391644
2442,123.766996,113.034371,98.334357,81.224213,148.738873,142.250394,112.400529,117.805625,116.273503,108.159465,...,105.816336,120.728867,113.714433,75.632429,133.272510,107.226803,128.451701,122.512200,96.992274,80.871394

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 9.90
Fold 1 - Mean Absolute Error (MAE): 2.49
Fold 1 - Root Mean Squared Error (RMSE): 3.15
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 10.79
Fold 2 - Mean Absolute Error (MAE): 2.53
Fold 2 - Root Mean Squared Error (RMSE): 3.28
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 10.67
Fold 3 - Mean Absolute Error (MAE): 2.51
Fold 3 - Root Mean Squared Error (RMSE): 3.27
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 11.04
Fold 4 - Mean Absolute Error (MAE): 2.58
Fold 4 - Root Mean Squared Error (RMSE): 3.32
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 10.12
Fold 5 - Mean Absolute Error (MAE): 2.49
Fold 5 - Root Mean Squared Error (RMSE): 3.18
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 10.51
Mean - Mean Absolute Error (MAE): 2.52
Mean - Root Mean Squared Error (RMSE): 3.24
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 92.27
Fold 1 - Mean Absolute Error (MAE): 6.02
Fold 1 - Root Mean Squared Error (RMSE): 9.61
Fold 1 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 89.46
Fold 2 - Mean Absolute Error (MAE): 5.92
Fold 2 - Root Mean Squared Error (RMSE): 9.46
Fold 2 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 100.02
Fold 3 - Mean Absolute Error (MAE): 6.30
Fold 3 - Root Mean Squared Error (RMSE): 10.00
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 85.03
Fold 4 - Mean Absolute Error (MAE): 5.71
Fold 4 - Root Mean Squared Error (RMSE): 9.22
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 98.29
Fold 5 - Mean Absolute Error (MAE): 6.34
Fold 5 - Root Mean Squared Error (RMSE): 9.91
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 93.01
Mean - Mean Absolute Error (MAE): 6.06
Mean - Root Mean Squared Error (RMSE): 9.64
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 20.85
Fold 1 - Mean Absolute Error (MAE): 3.53
Fold 1 - Root Mean Squared Error (RMSE): 4.57
Fold 1 - Time taken: 2.48 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 19.64
Fold 2 - Mean Absolute Error (MAE): 3.45
Fold 2 - Root Mean Squared Error (RMSE): 4.43
Fold 2 - Time taken: 2.55 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 18.71
Fold 3 - Mean Absolute Error (MAE): 3.41
Fold 3 - Root Mean Squared Error (RMSE): 4.33
Fold 3 - Time taken: 3.71 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 19.05
Fold 4 - Mean Absolute Error (MAE): 3.40
Fold 4 - Root Mean Squared Error (RMSE): 4.36
Fold 4 - Time taken: 3.70 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 18.71
Fold 5 - Mean Absolute Error (MAE): 3.43
Fold 5 - Root Mean Squared Error (RMSE): 4.33
Fold 5 - Time taken: 3.81 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 19.39
Mean - Mean Absolute Error (MAE): 3.44
Mean - Root Mean Squared Error (RMSE): 4.40
Mean - Time taken: 3.25 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.27
Fold 1 - Mean Absolute Error (MAE): 1.51
Fold 1 - Root Mean Squared Error (RMSE): 2.29
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.67
Fold 2 - Mean Absolute Error (MAE): 1.50
Fold 2 - Root Mean Squared Error (RMSE): 2.38
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 6.23
Fold 3 - Mean Absolute Error (MAE): 1.60
Fold 3 - Root Mean Squared Error (RMSE): 2.50
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 5.81
Fold 4 - Mean Absolute Error (MAE): 1.61
Fold 4 - Root Mean Squared Error (RMSE): 2.41
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 6.49
Fold 5 - Mean Absolute Error (MAE): 1.64
Fold 5 - Root Mean Squared Error (RMSE): 2.55
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.89
Mean - Mean Absolute Error (MAE): 1.57
Mean - Root Mean Squared Error (RMSE): 2.43
Mean - Time taken: 0.03 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 21.42
Fold 1 - Mean Absolute Error (MAE): 3.36
Fold 1 - Root Mean Squared Error (RMSE): 4.63
Fold 1 - Time taken: 1.97 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 20.30
Fold 2 - Mean Absolute Error (MAE): 3.29
Fold 2 - Root Mean Squared Error (RMSE): 4.51
Fold 2 - Time taken: 1.94 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 21.11
Fold 3 - Mean Absolute Error (MAE): 3.36
Fold 3 - Root Mean Squared Error (RMSE): 4.59
Fold 3 - Time taken: 1.96 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 24.36
Fold 4 - Mean Absolute Error (MAE): 3.58
Fold 4 - Root Mean Squared Error (RMSE): 4.94
Fold 4 - Time taken: 1.96 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 22.83
Fold 5 - Mean Absolute Error (MAE): 3.54
Fold 5 - Root Mean Squared Error (RMSE): 4.78
Fold 5 - Time taken: 1.96 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 22.00
Mean - Mean Absolute Error (MAE): 3.43
Mean - Root Mean Squared Error (RMSE): 4.69
Mean - Time taken: 1.96 seconds

# Saving the results to an Excel file

In [1]:
results_df.to_excel("Results__PL_scattered_48_frontback_200_iReg1.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_scattered_48_frontback_200_iReg1.xlsx file")

Results saved to Results__PL_scattered_48_frontback_200_iReg1.xlsx file