# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Smoothed path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,...,107.203207,119.753930,99.374723,130.509610,74.261665,114.452393,109.175534,135.113346,90.649533,122.847967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,...,119.411902,110.280775,131.083235,112.046128,103.479049,74.943352,138.581705,124.544305,114.741035,94.729096

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 16

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:16]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,sensor11,sensor12,sensor13,sensor14,sensor15,sensor16
0,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,79.551255,109.658522,121.671697,139.921001,108.602786,127.546015
1,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,79.551255,109.658522,121.671697,139.921001,108.602786,127.546015
2,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,79.551255,109.658522,121.671697,139.921001,108.602786,127.546015
3,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,79.551255,109.658522,121.671697,139.921001,108.602786,127.546015
4,103.365475,131.254765,82.406446,118.490072,124.741424,148.572789,110.782852,137.480311,101.466941,123.421399,79.551255,109.658522,121.671697,139.921001,108.602786,127.546015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,94.718210,69.185381,147.585950,136.705821,125.037299,112.888952
2439,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,94.718210,69.185381,147.585950,136.705821,125.037299,112.888952
2440,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,94.718210,69.185381,147.585950,136.705821,125.037299,112.888952
2441,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,94.718210,69.185381,147.585950,136.705821,125.037299,112.888952
2442,130.845198,115.244199,106.851047,78.347576,153.056587,140.522035,133.823333,116.302351,121.182268,110.310482,94.718210,69.185381,147.585950,136.705821,125.037299,112.888952

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,sensor11,sensor12,sensor13,sensor14,sensor15,sensor16
233,137.881517,153.165243,115.871574,137.406585,112.526032,135.466550,71.723841,110.006074,136.787768,148.064769,112.322269,127.722448,108.608393,127.014371,67.307544,97.115230
433,121.592208,139.058026,86.335605,112.792428,130.389895,146.267373,99.826221,119.987946,119.634796,130.704687,78.644619,101.426637,128.706525,138.671694,97.363297,112.775014
1430,145.771325,144.778557,117.656261,118.072187,126.463228,129.171448,86.779440,90.997365,140.201692,140.003560,110.601957,110.523669,120.868936,123.150815,79.892326,83.009180
307,127.945292,147.421209,113.727319,135.577414,104.027441,126.791389,81.781185,113.726384,127.379462,140.019466,112.588913,127.189370,101.168333,120.079944,77.426983,103.663742
2197,140.479449,130.043474,130.979969,115.610718,122.947593,107.437010,107.938768,88.593358,134.119687,126.435584,121.192466,112.663820,114.950063,105.034931,96.142969,81.773537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,131.484235,128.208485,110.374820,108.586940,125.997951,121.476007,103.909611,99.945705,125.277444,123.634429,101.552364,102.460416,121.132351,117.069731,96.760435,93.895482
1095,127.067786,131.636548,87.134422,99.243018,140.639940,147.382136,111.281736,118.231354,122.493099,125.273887,76.878343,89.055431,136.397261,141.561234,104.200710,109.011718
1130,123.972924,130.783089,84.240653,97.925160,144.913317,150.133795,114.828089,121.051632,119.591640,122.401914,74.593091,85.608880,141.128496,143.652257,109.998003,114.380211
1294,117.190655,120.592002,96.872234,101.981039,129.046835,133.089505,113.339273,117.095254,111.655741,113.163124,90.809776,94.717811,124.740016,126.921576,108.738702,110.944512
860,139.956869,150.417225,118.141071,130.418639,114.598147,127.566352,81.158577,98.930350,137.830975,141.822428,113.118031,122.269539,112.272043,119.466116,73.759383,88.432945

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9980735934701581
Mean Squared Error: 0.8525092049267903
Root Mean Squared Error: 0.9213255857174351
R2 Score: 0.9980735934701581
Mean Absolute Error: 0.745465407216336
Median Absolute Error: 0.6477460647134882
Explained Variance Score: 0.99807498188721
Time taken: 0.0034995079040527344
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.9979407961701372
Mean Squared Error: 1.2105684006411235
Root Mean Squared Error: 1.0864697991770083
R2 Score: 0.9979407961701372
Mean Absolute Error: 0.4971125193704427
Median Absolute Error: 0.3100584596216341
Explained Variance Score: 0.9979523061711454
Time taken: 0.014999866485595703
====================================================================================================
RandomForestRegressor
Accuracy: 0.9990787666456549
Mean Squared Error: 0.3486755953882605
Root Mean Squared Error: 0.5873233635625209
R2 Score: 0.9990787666456549
Mean Absolute Error: 0.2821751147119091
Median Absolute Error: 0.1347173822514757
Explained Variance Score: 0.9990808216850527
Time taken: 0.8504989147186279
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9997856365180691
Mean Squared Error: 0.0858282760092494
Root Mean Squared Error: 0.252790513011209
R2 Score: 0.9997856365180691
Mean Absolute Error: 0.17623844701710856
Median Absolute Error: 0.13891640061046076
Explained Variance Score: 0.9997864415189084
Time taken: 0.05800032615661621
====================================================================================================
XGBRegressor
Accuracy: 0.9980632564649667
Mean Squared Error: 0.9669315275959224
Root Mean Squared Error: 0.977073002273762
R2 Score: 0.9980632564649667
Mean Absolute Error: 0.5705435962116107
Median Absolute Error: 0.337070004012529
Explained Variance Score: 0.9980723091186174
Time taken: 0.34799957275390625
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.85
Fold 1 - Mean Absolute Error (MAE): 0.75
Fold 1 - Root Mean Squared Error (RMSE): 0.92
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.85
Fold 2 - Mean Absolute Error (MAE): 0.73
Fold 2 - Root Mean Squared Error (RMSE): 0.92
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.86
Fold 3 - Mean Absolute Error (MAE): 0.74
Fold 3 - Root Mean Squared Error (RMSE): 0.92
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.90
Fold 4 - Mean Absolute Error (MAE): 0.76
Fold 4 - Root Mean Squared Error (RMSE): 0.95
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.84
Fold 5 - Mean Absolute Error (MAE): 0.73
Fold 5 - Root Mean Squared Error (RMSE): 0.92
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 0.86
Mean MAE: 0.74
Mean RMSE: 0.93
Mean time: 0.00 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.96
Fold 1 - Mean Absolute Error (MAE): 0.48
Fold 1 - Root Mean Squared Error (RMSE): 0.98
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 2.44
Fold 2 - Mean Absolute Error (MAE): 0.57
Fold 2 - Root Mean Squared Error (RMSE): 1.56
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 4.98
Fold 3 - Mean Absolute Error (MAE): 0.64
Fold 3 - Root Mean Squared Error (RMSE): 2.23
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 3.47
Fold 4 - Mean Absolute Error (MAE): 0.58
Fold 4 - Root Mean Squared Error (RMSE): 1.86
Fold 4 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.19
Fold 5 - Mean Absolute Error (MAE): 0.49
Fold 5 - Root Mean Squared Error (RMSE): 1.09
Fold 5 - Time taken: 0.02 seconds
Mean MSE: 2.61
Mean MAE: 0.55
Mean RMSE: 1.55
Mean time: 0.02 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.32
Fold 1 - Mean Absolute Error (MAE): 0.27
Fold 1 - Root Mean Squared Error (RMSE): 0.57
Fold 1 - Time taken: 0.84 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.22
Fold 2 - Mean Absolute Error (MAE): 0.26
Fold 2 - Root Mean Squared Error (RMSE): 0.46
Fold 2 - Time taken: 0.85 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 1.08
Fold 3 - Mean Absolute Error (MAE): 0.34
Fold 3 - Root Mean Squared Error (RMSE): 1.04
Fold 3 - Time taken: 0.84 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.43
Fold 4 - Mean Absolute Error (MAE): 0.28
Fold 4 - Root Mean Squared Error (RMSE): 0.66
Fold 4 - Time taken: 0.84 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.13
Fold 5 - Mean Absolute Error (MAE): 0.22
Fold 5 - Root Mean Squared Error (RMSE): 0.36
Fold 5 - Time taken: 1.29 seconds
Mean MSE: 0.43
Mean MAE: 0.27
Mean RMSE: 0.62
Mean time: 0.93 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.07
Fold 1 - Mean Absolute Error (MAE): 0.17
Fold 1 - Root Mean Squared Error (RMSE): 0.27
Fold 1 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.10
Fold 2 - Mean Absolute Error (MAE): 0.18
Fold 2 - Root Mean Squared Error (RMSE): 0.31
Fold 2 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.10
Fold 3 - Mean Absolute Error (MAE): 0.19
Fold 3 - Root Mean Squared Error (RMSE): 0.32
Fold 3 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.10
Fold 4 - Mean Absolute Error (MAE): 0.19
Fold 4 - Root Mean Squared Error (RMSE): 0.31
Fold 4 - Time taken: 0.07 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.09
Fold 5 - Mean Absolute Error (MAE): 0.19
Fold 5 - Root Mean Squared Error (RMSE): 0.30
Fold 5 - Time taken: 0.07 seconds
Mean MSE: 0.09
Mean MAE: 0.18
Mean RMSE: 0.30
Mean time: 0.07 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.97
Fold 1 - Mean Absolute Error (MAE): 0.57
Fold 1 - Root Mean Squared Error (RMSE): 0.98
Fold 1 - Time taken: 6.21 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.35
Fold 2 - Mean Absolute Error (MAE): 0.57
Fold 2 - Root Mean Squared Error (RMSE): 1.16
Fold 2 - Time taken: 5.93 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.03
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 1.02
Fold 3 - Time taken: 5.94 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.00
Fold 4 - Mean Absolute Error (MAE): 0.54
Fold 4 - Root Mean Squared Error (RMSE): 1.00
Fold 4 - Time taken: 5.99 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.59
Fold 5 - Mean Absolute Error (MAE): 0.65
Fold 5 - Root Mean Squared Error (RMSE): 1.26
Fold 5 - Time taken: 6.43 seconds
Mean MSE: 1.19
Mean MAE: 0.58
Mean RMSE: 1.08
Mean time: 6.10 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Smoothed path loss - (1-16) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 0.85
Fold 1 - Mean Absolute Error (MAE): 0.75
Fold 1 - Root Mean Squared Error (RMSE): 0.92
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 0.85
Fold 2 - Mean Absolute Error (MAE): 0.73
Fold 2 - Root Mean Squared Error (RMSE): 0.92
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 0.86
Fold 3 - Mean Absolute Error (MAE): 0.74
Fold 3 - Root Mean Squared Error (RMSE): 0.92
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 0.90
Fold 4 - Mean Absolute Error (MAE): 0.76
Fold 4 - Root Mean Squared Error (RMSE): 0.95
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 0.84
Fold 5 - Mean Absolute Error (MAE): 0.73
Fold 5 - Root Mean Squared Error (RMSE): 0.92
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 0.86
Mean - Mean Absolute Error (MAE): 0.74
Mean - Root Mean Squared Error (RMSE): 0.93
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 0.92
Fold 1 - Mean Absolute Error (MAE): 0.47
Fold 1 - Root Mean Squared Error (RMSE): 0.96
Fold 1 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 1.22
Fold 2 - Mean Absolute Error (MAE): 0.50
Fold 2 - Root Mean Squared Error (RMSE): 1.10
Fold 2 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 4.04
Fold 3 - Mean Absolute Error (MAE): 0.60
Fold 3 - Root Mean Squared Error (RMSE): 2.01
Fold 3 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 4.00
Fold 4 - Mean Absolute Error (MAE): 0.65
Fold 4 - Root Mean Squared Error (RMSE): 2.00
Fold 4 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 1.05
Fold 5 - Mean Absolute Error (MAE): 0.48
Fold 5 - Root Mean Squared Error (RMSE): 1.03
Fold 5 - Time taken: 0.03 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 2.24
Mean - Mean Absolute Error (MAE): 0.54
Mean - Root Mean Squared Error (RMSE): 1.42
Mean - Time taken: 0.03 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 0.39
Fold 1 - Mean Absolute Error (MAE): 0.28
Fold 1 - Root Mean Squared Error (RMSE): 0.62
Fold 1 - Time taken: 1.51 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 0.19
Fold 2 - Mean Absolute Error (MAE): 0.24
Fold 2 - Root Mean Squared Error (RMSE): 0.43
Fold 2 - Time taken: 1.51 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 0.89
Fold 3 - Mean Absolute Error (MAE): 0.33
Fold 3 - Root Mean Squared Error (RMSE): 0.94
Fold 3 - Time taken: 1.51 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 0.46
Fold 4 - Mean Absolute Error (MAE): 0.28
Fold 4 - Root Mean Squared Error (RMSE): 0.68
Fold 4 - Time taken: 1.50 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 0.14
Fold 5 - Mean Absolute Error (MAE): 0.23
Fold 5 - Root Mean Squared Error (RMSE): 0.38
Fold 5 - Time taken: 1.54 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 0.41
Mean - Mean Absolute Error (MAE): 0.27
Mean - Root Mean Squared Error (RMSE): 0.61
Mean - Time taken: 1.51 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 0.07
Fold 1 - Mean Absolute Error (MAE): 0.17
Fold 1 - Root Mean Squared Error (RMSE): 0.27
Fold 1 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 0.10
Fold 2 - Mean Absolute Error (MAE): 0.18
Fold 2 - Root Mean Squared Error (RMSE): 0.31
Fold 2 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 0.10
Fold 3 - Mean Absolute Error (MAE): 0.19
Fold 3 - Root Mean Squared Error (RMSE): 0.32
Fold 3 - Time taken: 0.05 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 0.10
Fold 4 - Mean Absolute Error (MAE): 0.19
Fold 4 - Root Mean Squared Error (RMSE): 0.31
Fold 4 - Time taken: 0.06 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 0.09
Fold 5 - Mean Absolute Error (MAE): 0.19
Fold 5 - Root Mean Squared Error (RMSE): 0.30
Fold 5 - Time taken: 0.10 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 0.09
Mean - Mean Absolute Error (MAE): 0.18
Mean - Root Mean Squared Error (RMSE): 0.30
Mean - Time taken: 0.06 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 0.97
Fold 1 - Mean Absolute Error (MAE): 0.57
Fold 1 - Root Mean Squared Error (RMSE): 0.98
Fold 1 - Time taken: 9.84 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 1.35
Fold 2 - Mean Absolute Error (MAE): 0.57
Fold 2 - Root Mean Squared Error (RMSE): 1.16
Fold 2 - Time taken: 5.89 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 1.03
Fold 3 - Mean Absolute Error (MAE): 0.54
Fold 3 - Root Mean Squared Error (RMSE): 1.02
Fold 3 - Time taken: 5.78 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 1.00
Fold 4 - Mean Absolute Error (MAE): 0.54
Fold 4 - Root Mean Squared Error (RMSE): 1.00
Fold 4 - Time taken: 5.89 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 1.59
Fold 5 - Mean Absolute Error (MAE): 0.65
Fold 5 - Root Mean Squared Error (RMSE): 1.26
Fold 5 - Time taken: 5.78 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 1.19
Mean - Mean Absolute Error (MAE): 0.58
Mean - Root Mean Squared Error (RMSE): 1.08
Mean - Time taken: 6.64 seconds
Results saved to results.xlsx file