# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('Scattered path loss of 48 sensors for 2443 positions.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280,95.879983,120.538335,...,109.733925,122.659778,95.395578,130.490611,73.119448,121.722946,104.559876,137.225660,91.041703,127.652224
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411,97.747726,127.941590,...,113.915353,123.190051,95.157075,127.762477,66.005689,115.881671,107.128477,140.352729,86.947794,119.210396
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604,102.738553,122.522861,...,112.052375,117.562515,99.313642,128.192048,75.164417,116.706805,112.276377,129.772121,88.276306,117.740004
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507,98.226181,122.213773,...,108.861984,129.042510,98.180222,129.344039,66.522773,117.580686,107.813133,134.786828,91.081817,118.908161
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840,96.138273,128.801601,...,108.706859,119.970422,100.514277,126.900903,71.984768,110.931963,113.277748,139.563546,92.386548,129.117372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302,120.576864,112.474493,...,119.309378,112.129281,133.167988,114.383990,102.902100,74.953746,136.775728,135.511864,113.860294,97.289917
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856,117.611405,97.729138,...,119.776043,109.341785,134.167797,108.758001,97.232046,76.553890,131.527636,120.620501,114.793561,86.316080
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822,121.482318,115.272484,...,124.257271,108.008908,124.793498,110.650887,110.008857,71.785029,141.782071,125.802032,113.221141,91.163433
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568,118.499662,104.549275,...,125.544587,114.946916,128.766695,114.402412,100.797834,77.919668,139.414337,117.483786,123.049769,91.451389
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240,119.649711,114.469436,...,120.001152,109.766753,125.244051,114.664490,110.627432,76.722995,138.251458,128.808403,123.226069,96.901824

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 8

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:8]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
0,103.267633,131.597806,81.831203,108.480113,126.401200,153.464898,112.979443,138.850280
1,91.665371,134.314718,83.926980,126.167508,127.048010,147.329908,113.967891,144.590411
2,108.052816,132.300121,76.009308,116.964033,132.173743,143.051777,115.162722,137.676604
3,101.053301,127.103974,84.735175,115.929306,118.353146,149.874228,106.017232,134.139507
4,108.955215,128.747209,82.213517,116.666273,125.771908,153.445316,111.663266,140.358840
...,...,...,...,...,...,...,...,...
2438,128.179344,114.641972,105.710144,88.287079,149.165563,137.537974,133.750673,112.015302
2439,126.365931,110.972446,103.198207,73.414657,146.420909,140.802299,136.087553,119.668856
2440,124.285145,103.360797,109.290753,79.003261,151.453751,138.577223,133.219135,111.313822
2441,128.455467,113.305564,120.534195,70.567774,150.202237,147.104822,128.145483,115.972568
2442,122.108331,117.023437,102.527909,87.494457,151.737028,140.752720,139.551852,113.287240

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
233,136.310276,150.384808,115.241974,137.637955,117.291541,146.146202,78.341112,97.943548
433,117.216199,143.936832,85.941792,113.718086,129.516070,143.437491,89.314080,120.160527
1430,146.817294,150.086441,121.703266,124.232207,123.061674,124.593387,81.544715,90.485171
307,125.850460,140.721249,119.845559,134.493230,102.363626,129.254969,79.529738,117.701210
2197,139.014239,128.180114,132.661534,120.944083,119.856020,100.881685,109.353318,87.625060
...,...,...,...,...,...,...,...,...
1638,130.751581,128.682978,105.120199,100.689118,129.783160,129.376056,105.830734,109.113527
1095,123.885788,139.526533,84.737342,96.710272,137.029086,149.761441,114.098792,116.684965
1130,117.705787,127.908987,86.522797,106.445743,143.134803,148.555034,113.875577,122.116334
1294,120.007510,126.895272,107.170011,102.032684,125.874924,127.836227,116.742468,115.698891
860,142.091967,144.929032,117.727627,131.181538,121.255144,126.722988,87.921926,93.251797

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9082257578377962
Mean Squared Error: 40.027374976720324
Root Mean Squared Error: 6.325813371840659
R2 Score: 0.9082257578377962
Mean Absolute Error: 5.1278918635098165
Median Absolute Error: 4.32621008163333
Explained Variance Score: 0.9083015014342087
Time taken: 0.003476858139038086
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.770910860623013
Mean Squared Error: 104.34073392066797
Root Mean Squared Error: 10.211968531248564
R2 Score: 0.770910860623013
Mean Absolute Error: 6.752041698883598
Median Absolute Error: 3.968612898151236
Explained Variance Score: 0.7713942352916544
Time taken: 0.010429859161376953
====================================================================================================
RandomForestRegressor
Accuracy: 0.9091266357540219
Mean Squared Error: 41.09793174653995
Root Mean Squared Error: 6.410159633413325
R2 Score: 0.9091266357540219
Mean Absolute Error: 4.8273228349362665
Median Absolute Error: 3.580277942450225
Explained Variance Score: 0.909128747452033
Time taken: 0.5732364654541016
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9314743239253659
Mean Squared Error: 32.470521668583096
Root Mean Squared Error: 5.678759912870427
R2 Score: 0.9314743239253659
Mean Absolute Error: 3.9502523549767248
Median Absolute Error: 2.6052856008383274
Explained Variance Score: 0.931547546823342
Time taken: 0.005463361740112305
====================================================================================================
XGBRegressor
Accuracy: 0.9027852880394956
Mean Squared Error: 44.958855921503705
Root Mean Squared Error: 6.70259442971252
R2 Score: 0.9027852880394956
Mean Absolute Error: 5.027825553336636
Median Absolute Error: 3.8499362974236853
Explained Variance Score: 0.9028364237604541
Time taken: 0.23743295669555664
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 40.03
Fold 1 - Mean Absolute Error (MAE): 5.13
Fold 1 - Root Mean Squared Error (RMSE): 6.33
Fold 1 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 38.80
Fold 2 - Mean Absolute Error (MAE): 4.96
Fold 2 - Root Mean Squared Error (RMSE): 6.23
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 39.52
Fold 3 - Mean Absolute Error (MAE): 5.06
Fold 3 - Root Mean Squared Error (RMSE): 6.29
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 40.09
Fold 4 - Mean Absolute Error (MAE): 4.98
Fold 4 - Root Mean Squared Error (RMSE): 6.33
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 38.65
Fold 5 - Mean Absolute Error (MAE): 5.00
Fold 5 - Root Mean Squared Error (RMSE): 6.22
Fold 5 - Time taken: 0.00 seconds
Mean MSE: 39.42
Mean MAE: 5.03
Mean RMSE: 6.28
Mean time: 0.00 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 104.44
Fold 1 - Mean Absolute Error (MAE): 6.73
Fold 1 - Root Mean Squared Error (RMSE): 10.22
Fold 1 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 97.95
Fold 2 - Mean Absolute Error (MAE): 6.34
Fold 2 - Root Mean Squared Error (RMSE): 9.90
Fold 2 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 107.97
Fold 3 - Mean Absolute Error (MAE): 6.85
Fold 3 - Root Mean Squared Error (RMSE): 10.39
Fold 3 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 104.94
Fold 4 - Mean Absolute Error (MAE): 6.75
Fold 4 - Root Mean Squared Error (RMSE): 10.24
Fold 4 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 104.65
Fold 5 - Mean Absolute Error (MAE): 6.56
Fold 5 - Root Mean Squared Error (RMSE): 10.23
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 103.99
Mean MAE: 6.65
Mean RMSE: 10.20
Mean time: 0.01 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 40.99
Fold 1 - Mean Absolute Error (MAE): 4.81
Fold 1 - Root Mean Squared Error (RMSE): 6.40
Fold 1 - Time taken: 0.57 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 37.16
Fold 2 - Mean Absolute Error (MAE): 4.50
Fold 2 - Root Mean Squared Error (RMSE): 6.10
Fold 2 - Time taken: 0.57 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 40.17
Fold 3 - Mean Absolute Error (MAE): 4.71
Fold 3 - Root Mean Squared Error (RMSE): 6.34
Fold 3 - Time taken: 0.59 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 42.80
Fold 4 - Mean Absolute Error (MAE): 4.91
Fold 4 - Root Mean Squared Error (RMSE): 6.54
Fold 4 - Time taken: 0.61 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 39.53
Fold 5 - Mean Absolute Error (MAE): 4.76
Fold 5 - Root Mean Squared Error (RMSE): 6.29
Fold 5 - Time taken: 0.62 seconds
Mean MSE: 40.13
Mean MAE: 4.74
Mean RMSE: 6.33
Mean time: 0.59 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 32.47
Fold 1 - Mean Absolute Error (MAE): 3.95
Fold 1 - Root Mean Squared Error (RMSE): 5.70
Fold 1 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 31.32
Fold 2 - Mean Absolute Error (MAE): 3.80
Fold 2 - Root Mean Squared Error (RMSE): 5.60
Fold 2 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 34.20
Fold 3 - Mean Absolute Error (MAE): 4.10
Fold 3 - Root Mean Squared Error (RMSE): 5.85
Fold 3 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 33.11
Fold 4 - Mean Absolute Error (MAE): 3.96
Fold 4 - Root Mean Squared Error (RMSE): 5.75
Fold 4 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 30.44
Fold 5 - Mean Absolute Error (MAE): 3.82
Fold 5 - Root Mean Squared Error (RMSE): 5.52
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 32.31
Mean MAE: 3.93
Mean RMSE: 5.68
Mean time: 0.01 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 44.96
Fold 1 - Mean Absolute Error (MAE): 5.03
Fold 1 - Root Mean Squared Error (RMSE): 6.71
Fold 1 - Time taken: 0.23 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 41.33
Fold 2 - Mean Absolute Error (MAE): 4.81
Fold 2 - Root Mean Squared Error (RMSE): 6.43
Fold 2 - Time taken: 0.25 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 45.58
Fold 3 - Mean Absolute Error (MAE): 4.97
Fold 3 - Root Mean Squared Error (RMSE): 6.75
Fold 3 - Time taken: 0.29 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 46.87
Fold 4 - Mean Absolute Error (MAE): 5.06
Fold 4 - Root Mean Squared Error (RMSE): 6.85
Fold 4 - Time taken: 0.67 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 46.27
Fold 5 - Mean Absolute Error (MAE): 5.02
Fold 5 - Root Mean Squared Error (RMSE): 6.80
Fold 5 - Time taken: 0.65 seconds
Mean MSE: 45.00
Mean MAE: 4.98
Mean RMSE: 6.71
Mean time: 0.42 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Scattered path loss - (1-8) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 40.03
Fold 1 - Mean Absolute Error (MAE): 5.13
Fold 1 - Root Mean Squared Error (RMSE): 6.33
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 38.80
Fold 2 - Mean Absolute Error (MAE): 4.96
Fold 2 - Root Mean Squared Error (RMSE): 6.23
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 39.52
Fold 3 - Mean Absolute Error (MAE): 5.06
Fold 3 - Root Mean Squared Error (RMSE): 6.29
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 40.09
Fold 4 - Mean Absolute Error (MAE): 4.98
Fold 4 - Root Mean Squared Error (RMSE): 6.33
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 38.65
Fold 5 - Mean Absolute Error (MAE): 5.00
Fold 5 - Root Mean Squared Error (RMSE): 6.22
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 39.42
Mean - Mean Absolute Error (MAE): 5.03
Mean - Root Mean Squared Error (RMSE): 6.28
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 102.93
Fold 1 - Mean Absolute Error (MAE): 6.67
Fold 1 - Root Mean Squared Error (RMSE): 10.15
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 98.20
Fold 2 - Mean Absolute Error (MAE): 6.40
Fold 2 - Root Mean Squared Error (RMSE): 9.91
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 111.44
Fold 3 - Mean Absolute Error (MAE): 7.00
Fold 3 - Root Mean Squared Error (RMSE): 10.56
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 108.79
Fold 4 - Mean Absolute Error (MAE): 6.92
Fold 4 - Root Mean Squared Error (RMSE): 10.43
Fold 4 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 102.96
Fold 5 - Mean Absolute Error (MAE): 6.50
Fold 5 - Root Mean Squared Error (RMSE): 10.15
Fold 5 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 104.87
Mean - Mean Absolute Error (MAE): 6.70
Mean - Root Mean Squared Error (RMSE): 10.24
Mean - Time taken: 0.02 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 40.44
Fold 1 - Mean Absolute Error (MAE): 4.81
Fold 1 - Root Mean Squared Error (RMSE): 6.36
Fold 1 - Time taken: 0.93 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 36.08
Fold 2 - Mean Absolute Error (MAE): 4.46
Fold 2 - Root Mean Squared Error (RMSE): 6.01
Fold 2 - Time taken: 0.68 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 40.51
Fold 3 - Mean Absolute Error (MAE): 4.75
Fold 3 - Root Mean Squared Error (RMSE): 6.36
Fold 3 - Time taken: 0.88 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 42.35
Fold 4 - Mean Absolute Error (MAE): 4.89
Fold 4 - Root Mean Squared Error (RMSE): 6.51
Fold 4 - Time taken: 0.90 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 39.87
Fold 5 - Mean Absolute Error (MAE): 4.78
Fold 5 - Root Mean Squared Error (RMSE): 6.31
Fold 5 - Time taken: 0.86 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 39.85
Mean - Mean Absolute Error (MAE): 4.74
Mean - Root Mean Squared Error (RMSE): 6.31
Mean - Time taken: 0.85 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 32.47
Fold 1 - Mean Absolute Error (MAE): 3.95
Fold 1 - Root Mean Squared Error (RMSE): 5.70
Fold 1 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 31.32
Fold 2 - Mean Absolute Error (MAE): 3.80
Fold 2 - Root Mean Squared Error (RMSE): 5.60
Fold 2 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 34.20
Fold 3 - Mean Absolute Error (MAE): 4.10
Fold 3 - Root Mean Squared Error (RMSE): 5.85
Fold 3 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 33.11
Fold 4 - Mean Absolute Error (MAE): 3.96
Fold 4 - Root Mean Squared Error (RMSE): 5.75
Fold 4 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 30.44
Fold 5 - Mean Absolute Error (MAE): 3.82
Fold 5 - Root Mean Squared Error (RMSE): 5.52
Fold 5 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 32.31
Mean - Mean Absolute Error (MAE): 3.93
Mean - Root Mean Squared Error (RMSE): 5.68
Mean - Time taken: 0.01 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 44.96
Fold 1 - Mean Absolute Error (MAE): 5.03
Fold 1 - Root Mean Squared Error (RMSE): 6.71
Fold 1 - Time taken: 0.66 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 41.33
Fold 2 - Mean Absolute Error (MAE): 4.81
Fold 2 - Root Mean Squared Error (RMSE): 6.43
Fold 2 - Time taken: 0.65 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 45.58
Fold 3 - Mean Absolute Error (MAE): 4.97
Fold 3 - Root Mean Squared Error (RMSE): 6.75
Fold 3 - Time taken: 0.64 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 46.87
Fold 4 - Mean Absolute Error (MAE): 5.06
Fold 4 - Root Mean Squared Error (RMSE): 6.85
Fold 4 - Time taken: 0.66 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 46.27
Fold 5 - Mean Absolute Error (MAE): 5.02
Fold 5 - Root Mean Squared Error (RMSE): 6.80
Fold 5 - Time taken: 0.65 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 45.00
Mean - Mean Absolute Error (MAE): 4.98
Mean - Root Mean Squared Error (RMSE): 6.71
Mean - Time taken: 0.65 seconds
Results saved to results.xlsx file