# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_scattered_48_reg_frontback_random.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,99.531742,113.249339,103.217626,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,98.810013,101.878517,104.363022,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,94.813690,107.732324,105.612958,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,105.018314,104.822431,101.264143,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,106.276715,100.853621,105.035107,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,108.898729,120.478896,116.600259,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,96.454590,123.164933,106.694996,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,103.114188,117.380927,101.377838,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,110.786983,116.579398,107.851790,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,100.983003,118.492095,104.809426,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,99.531742,113.249339,103.217626,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,98.810013,101.878517,104.363022,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,94.813690,107.732324,105.612958,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,105.018314,104.822431,101.264143,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,106.276715,100.853621,105.035107,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,108.898729,120.478896,116.600259,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,96.454590,123.164933,106.694996,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,103.114188,117.380927,101.377838,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,110.786983,116.579398,107.851790,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,100.983003,118.492095,104.809426,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Taking Sensor 01 - Sensor 8

In [13]:
sensors_data = pd.concat([sensors_data.iloc[:,:8]], axis=1)
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438
...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334

# Split the data into training and testing sets

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sensors_data, position_data, test_size=0.2, random_state=42)

In [15]:
X_train

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8
233,136.164750,149.108142,112.379818,140.010783,109.783103,135.230600,78.553379,117.315729
433,115.958460,147.186902,80.822686,106.542283,125.007792,149.718650,95.190513,125.289858
1430,146.294977,145.407890,119.099522,117.404047,123.885067,128.037754,92.529499,80.534426
307,130.375317,147.637939,108.222918,131.782736,104.975746,125.569529,83.407176,116.808935
2197,134.716381,129.102858,123.121840,115.380662,121.281644,112.426340,104.676744,82.936161
...,...,...,...,...,...,...,...,...
1638,122.743765,124.399168,114.224411,112.028473,122.442929,124.224856,102.540907,105.173175
1095,124.757025,135.628184,85.000100,93.024058,142.328508,148.561824,107.900975,123.587976
1130,121.959052,122.872277,88.693968,96.506766,143.455314,143.557760,112.738594,125.943019
1294,112.726132,121.645738,98.338235,107.071511,128.040335,134.369897,105.657097,120.085881
860,131.866783,137.478379,117.656440,132.782295,123.379984,126.780661,76.547049,95.626900

In [16]:
y_train

          Pos X      Pos Y  Pos Z
233   59.678117  54.115562 -50.68
433  -19.191177  62.122007 -42.68
1430  45.890531  69.708995  -2.80
307   48.255475  30.881811 -47.72
2197  46.396180  30.387490  27.88
...         ...        ...    ...
1638  11.378450  42.552019   5.52
1095 -36.900143  69.397796 -16.20
1130 -50.886002  67.974162 -14.80
1294 -28.195387  33.407817  -8.24
860   59.591095  54.630197 -25.60

[1954 rows x 3 columns]

# Machine Learning

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from sklearn.metrics import explained_variance_score, max_error, mean_squared_log_error

In [18]:
# Initialize the models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(),  XGBRegressor()]

In [19]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, explained_variance_score
import time

# Train and evaluate each model
for model in models:
    start_time = time.time()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    end_time = time.time()
    
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    
    print(type(model).__name__)
    print("Accuracy:", model.score(X_test, y_test))
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("Root Mean Squared Error:", rmse)
    print("R2 Score:", r2_score(y_test, y_pred))
    print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
    print("Median Absolute Error:", median_absolute_error(y_test, y_pred))
    print("Explained Variance Score:", explained_variance_score(y_test, y_pred))
    print("Time taken:", end_time - start_time)
    print("="*100)

LinearRegression
Accuracy: 0.9189933463544077
Mean Squared Error: 38.976214973600065
Root Mean Squared Error: 6.23554278238534
R2 Score: 0.9189933463544077
Mean Absolute Error: 4.983770113730061
Median Absolute Error: 4.191307786943981
Explained Variance Score: 0.9193892497581757
Time taken: 0.0034995079040527344
====================================================================================================
DecisionTreeRegressor
Accuracy: 0.8002270114403812
Mean Squared Error: 104.95463655766675
Root Mean Squared Error: 10.187236183076587
R2 Score: 0.8002270114403812
Mean Absolute Error: 6.692007661862384
Median Absolute Error: 3.616298644285722
Explained Variance Score: 0.8007362342263374
Time taken: 0.010000228881835938
====================================================================================================
RandomForestRegressor
Accuracy: 0.9265345543785591
Mean Squared Error: 37.51008299023407
Root Mean Squared Error: 6.1034463175462905
R2 Score: 0.9265345543785591
Mean Absolute Error: 4.530699302524771
Median Absolute Error: 3.2871380451518846
Explained Variance Score: 0.9266064751630942
Time taken: 0.5810470581054688
====================================================================================================
KNeighborsRegressor
Accuracy: 0.9370048284450375
Mean Squared Error: 32.918282352075856
Root Mean Squared Error: 5.710874332937842
R2 Score: 0.9370048284450375
Mean Absolute Error: 3.8328069369000928
Median Absolute Error: 2.2966908887671766
Explained Variance Score: 0.9370059373619855
Time taken: 0.005499839782714844
====================================================================================================
XGBRegressor
Accuracy: 0.9141230893849542
Mean Squared Error: 44.55969864791971
Root Mean Squared Error: 6.642821737845903
R2 Score: 0.9141230893849542
Mean Absolute Error: 4.887488612808948
Median Absolute Error: 3.4038499337480133
Explained Variance Score: 0.9142041203283716
Time taken: 0.4780433177947998
====================================================================================================

# Cross Validation

In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

#Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

#Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Print the mean results of the folds
    print(f"Mean MSE: {mean_mse:.2f}")
    print(f"Mean MAE: {mean_mae:.2f}")
    print(f"Mean RMSE: {mean_rmse:.2f}")
    print(f"Mean time: {mean_time:.2f} seconds")
    print("-" * 50)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 38.98
Fold 1 - Mean Absolute Error (MAE): 4.98
Fold 1 - Root Mean Squared Error (RMSE): 6.24
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 40.08
Fold 2 - Mean Absolute Error (MAE): 5.04
Fold 2 - Root Mean Squared Error (RMSE): 6.33
Fold 2 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 37.72
Fold 3 - Mean Absolute Error (MAE): 4.91
Fold 3 - Root Mean Squared Error (RMSE): 6.14
Fold 3 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 43.59
Fold 4 - Mean Absolute Error (MAE): 5.26
Fold 4 - Root Mean Squared Error (RMSE): 6.60
Fold 4 - Time taken: 0.00 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 37.82
Fold 5 - Mean Absolute Error (MAE): 4.88
Fold 5 - Root Mean Squared Error (RMSE): 6.15
Fold 5 - Time taken: 0.00 seconds
Mean MSE: 39.64
Mean MAE: 5.02
Mean RMSE: 6.29
Mean time: 0.00 seconds
--------------------------------------------------
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 105.27
Fold 1 - Mean Absolute Error (MAE): 6.70
Fold 1 - Root Mean Squared Error (RMSE): 10.26
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 105.71
Fold 2 - Mean Absolute Error (MAE): 6.64
Fold 2 - Root Mean Squared Error (RMSE): 10.28
Fold 2 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 101.51
Fold 3 - Mean Absolute Error (MAE): 6.51
Fold 3 - Root Mean Squared Error (RMSE): 10.07
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 102.83
Fold 4 - Mean Absolute Error (MAE): 6.73
Fold 4 - Root Mean Squared Error (RMSE): 10.14
Fold 4 - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 101.27
Fold 5 - Mean Absolute Error (MAE): 6.57
Fold 5 - Root Mean Squared Error (RMSE): 10.06
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 103.32
Mean MAE: 6.63
Mean RMSE: 10.16
Mean time: 0.01 seconds
--------------------------------------------------
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 37.88
Fold 1 - Mean Absolute Error (MAE): 4.53
Fold 1 - Root Mean Squared Error (RMSE): 6.15
Fold 1 - Time taken: 0.58 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 40.58
Fold 2 - Mean Absolute Error (MAE): 4.67
Fold 2 - Root Mean Squared Error (RMSE): 6.37
Fold 2 - Time taken: 0.59 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 38.19
Fold 3 - Mean Absolute Error (MAE): 4.57
Fold 3 - Root Mean Squared Error (RMSE): 6.18
Fold 3 - Time taken: 0.73 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 44.08
Fold 4 - Mean Absolute Error (MAE): 4.99
Fold 4 - Root Mean Squared Error (RMSE): 6.64
Fold 4 - Time taken: 1.33 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 36.56
Fold 5 - Mean Absolute Error (MAE): 4.51
Fold 5 - Root Mean Squared Error (RMSE): 6.05
Fold 5 - Time taken: 1.42 seconds
Mean MSE: 39.46
Mean MAE: 4.65
Mean RMSE: 6.28
Mean time: 0.93 seconds
--------------------------------------------------
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 32.92
Fold 1 - Mean Absolute Error (MAE): 3.83
Fold 1 - Root Mean Squared Error (RMSE): 5.74
Fold 1 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 32.03
Fold 2 - Mean Absolute Error (MAE): 3.89
Fold 2 - Root Mean Squared Error (RMSE): 5.66
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 31.54
Fold 3 - Mean Absolute Error (MAE): 3.81
Fold 3 - Root Mean Squared Error (RMSE): 5.62
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 35.81
Fold 4 - Mean Absolute Error (MAE): 4.14
Fold 4 - Root Mean Squared Error (RMSE): 5.98
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 28.37
Fold 5 - Mean Absolute Error (MAE): 3.70
Fold 5 - Root Mean Squared Error (RMSE): 5.33
Fold 5 - Time taken: 0.01 seconds
Mean MSE: 32.13
Mean MAE: 3.88
Mean RMSE: 5.66
Mean time: 0.02 seconds
--------------------------------------------------
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 44.56
Fold 1 - Mean Absolute Error (MAE): 4.89
Fold 1 - Root Mean Squared Error (RMSE): 6.68
Fold 1 - Time taken: 12.86 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 42.91
Fold 2 - Mean Absolute Error (MAE): 4.83
Fold 2 - Root Mean Squared Error (RMSE): 6.55
Fold 2 - Time taken: 7.06 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 45.81
Fold 3 - Mean Absolute Error (MAE): 5.03
Fold 3 - Root Mean Squared Error (RMSE): 6.77
Fold 3 - Time taken: 9.79 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 48.24
Fold 4 - Mean Absolute Error (MAE): 5.17
Fold 4 - Root Mean Squared Error (RMSE): 6.95
Fold 4 - Time taken: 28.12 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 43.76
Fold 5 - Mean Absolute Error (MAE): 4.89
Fold 5 - Root Mean Squared Error (RMSE): 6.61
Fold 5 - Time taken: 16.60 seconds
Mean MSE: 45.06
Mean MAE: 4.96
Mean RMSE: 6.71
Mean time: 14.89 seconds
--------------------------------------------------

# Excel File Conversion

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score, mean_absolute_error
import time


X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

#Save the results to an Excel file
results_df.to_excel("Scattered path loss - (1-8) results.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to results.xlsx file")

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 38.98
Fold 1 - Mean Absolute Error (MAE): 4.98
Fold 1 - Root Mean Squared Error (RMSE): 6.24
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 40.08
Fold 2 - Mean Absolute Error (MAE): 5.04
Fold 2 - Root Mean Squared Error (RMSE): 6.33
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 37.72
Fold 3 - Mean Absolute Error (MAE): 4.91
Fold 3 - Root Mean Squared Error (RMSE): 6.14
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 43.59
Fold 4 - Mean Absolute Error (MAE): 5.26
Fold 4 - Root Mean Squared Error (RMSE): 6.60
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 37.82
Fold 5 - Mean Absolute Error (MAE): 4.88
Fold 5 - Root Mean Squared Error (RMSE): 6.15
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 39.64
Mean - Mean Absolute Error (MAE): 5.02
Mean - Root Mean Squared Error (RMSE): 6.29
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 104.25
Fold 1 - Mean Absolute Error (MAE): 6.59
Fold 1 - Root Mean Squared Error (RMSE): 10.21
Fold 1 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 106.16
Fold 2 - Mean Absolute Error (MAE): 6.69
Fold 2 - Root Mean Squared Error (RMSE): 10.30
Fold 2 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 97.52
Fold 3 - Mean Absolute Error (MAE): 6.34
Fold 3 - Root Mean Squared Error (RMSE): 9.88
Fold 3 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 103.66
Fold 4 - Mean Absolute Error (MAE): 6.78
Fold 4 - Root Mean Squared Error (RMSE): 10.18
Fold 4 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 98.58
Fold 5 - Mean Absolute Error (MAE): 6.34
Fold 5 - Root Mean Squared Error (RMSE): 9.93
Fold 5 - Time taken: 0.02 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 102.03
Mean - Mean Absolute Error (MAE): 6.55
Mean - Root Mean Squared Error (RMSE): 10.10
Mean - Time taken: 0.02 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 37.69
Fold 1 - Mean Absolute Error (MAE): 4.54
Fold 1 - Root Mean Squared Error (RMSE): 6.14
Fold 1 - Time taken: 1.01 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 39.82
Fold 2 - Mean Absolute Error (MAE): 4.62
Fold 2 - Root Mean Squared Error (RMSE): 6.31
Fold 2 - Time taken: 1.01 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 36.79
Fold 3 - Mean Absolute Error (MAE): 4.50
Fold 3 - Root Mean Squared Error (RMSE): 6.07
Fold 3 - Time taken: 1.02 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 43.57
Fold 4 - Mean Absolute Error (MAE): 4.95
Fold 4 - Root Mean Squared Error (RMSE): 6.60
Fold 4 - Time taken: 1.03 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 36.29
Fold 5 - Mean Absolute Error (MAE): 4.47
Fold 5 - Root Mean Squared Error (RMSE): 6.02
Fold 5 - Time taken: 1.04 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 38.83
Mean - Mean Absolute Error (MAE): 4.62
Mean - Root Mean Squared Error (RMSE): 6.23
Mean - Time taken: 1.02 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 32.92
Fold 1 - Mean Absolute Error (MAE): 3.83
Fold 1 - Root Mean Squared Error (RMSE): 5.74
Fold 1 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 32.03
Fold 2 - Mean Absolute Error (MAE): 3.89
Fold 2 - Root Mean Squared Error (RMSE): 5.66
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 31.54
Fold 3 - Mean Absolute Error (MAE): 3.81
Fold 3 - Root Mean Squared Error (RMSE): 5.62
Fold 3 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 35.81
Fold 4 - Mean Absolute Error (MAE): 4.14
Fold 4 - Root Mean Squared Error (RMSE): 5.98
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 28.37
Fold 5 - Mean Absolute Error (MAE): 3.70
Fold 5 - Root Mean Squared Error (RMSE): 5.33
Fold 5 - Time taken: 0.01 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 32.13
Mean - Mean Absolute Error (MAE): 3.88
Mean - Root Mean Squared Error (RMSE): 5.66
Mean - Time taken: 0.01 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 44.56
Fold 1 - Mean Absolute Error (MAE): 4.89
Fold 1 - Root Mean Squared Error (RMSE): 6.68
Fold 1 - Time taken: 12.10 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 42.91
Fold 2 - Mean Absolute Error (MAE): 4.83
Fold 2 - Root Mean Squared Error (RMSE): 6.55
Fold 2 - Time taken: 38.02 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 45.81
Fold 3 - Mean Absolute Error (MAE): 5.03
Fold 3 - Root Mean Squared Error (RMSE): 6.77
Fold 3 - Time taken: 15.16 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 48.24
Fold 4 - Mean Absolute Error (MAE): 5.17
Fold 4 - Root Mean Squared Error (RMSE): 6.95
Fold 4 - Time taken: 18.25 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 43.76
Fold 5 - Mean Absolute Error (MAE): 4.89
Fold 5 - Root Mean Squared Error (RMSE): 6.61
Fold 5 - Time taken: 16.31 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 45.06
Mean - Mean Absolute Error (MAE): 4.96
Mean - Root Mean Squared Error (RMSE): 6.71
Mean - Time taken: 19.97 seconds
Results saved to results.xlsx file