# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_scattered_48_reg_frontback_random.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,99.531742,113.249339,103.217626,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,98.810013,101.878517,104.363022,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,94.813690,107.732324,105.612958,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,105.018314,104.822431,101.264143,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,106.276715,100.853621,105.035107,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,108.898729,120.478896,116.600259,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,96.454590,123.164933,106.694996,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,103.114188,117.380927,101.377838,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,110.786983,116.579398,107.851790,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,100.983003,118.492095,104.809426,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,110.711268,129.230445,75.463322,113.511095,121.694411,145.984667,114.347158,128.542893,102.019857,113.593544,...,99.531742,113.249339,103.217626,94.761444,132.609164,111.689942,101.381255,130.206469,81.830871,124.085931
1,95.702235,141.424797,85.373816,116.378093,125.321930,150.329013,112.922390,143.549881,105.991225,115.547599,...,98.810013,101.878517,104.363022,95.188697,135.571095,116.688400,104.392935,129.574346,83.108609,122.941519
2,103.938672,141.003192,85.000567,118.441676,127.472223,153.874649,109.590742,137.516658,111.940238,115.044055,...,94.813690,107.732324,105.612958,91.754305,130.180684,118.154075,96.420825,136.853674,86.217879,108.149710
3,102.529665,129.153521,82.754072,115.081102,126.914194,151.456218,112.408224,137.247646,95.139448,117.519283,...,105.018314,104.822431,101.264143,92.272692,122.196334,108.886693,98.570967,134.395116,74.549678,119.192962
4,105.295093,132.886683,84.703097,113.640929,130.131858,149.111901,114.497900,133.147438,101.365566,121.325542,...,106.276715,100.853621,105.035107,85.446182,127.155714,109.598921,105.013219,137.352870,90.788077,119.918510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.039673,107.624018,112.220684,75.200003,157.196528,144.639356,123.040753,120.294057,117.764474,104.608783,...,108.898729,120.478896,116.600259,62.850918,131.226678,118.673757,128.380150,110.000203,115.007727,79.265172
2439,132.004125,116.206713,111.118276,74.674690,153.494497,148.584344,128.491874,122.094259,117.024451,105.852683,...,96.454590,123.164933,106.694996,69.544645,134.674641,114.798618,136.957658,119.512745,106.341847,86.368770
2440,123.050332,111.866013,106.142539,80.785180,151.950031,143.995262,130.851418,118.303942,115.305973,102.571869,...,103.114188,117.380927,101.377838,78.176408,137.536286,114.722864,133.353450,111.999111,107.458463,82.722789
2441,129.807045,107.722496,106.922565,74.786681,156.269596,139.113293,140.649493,123.911561,107.046543,102.337785,...,110.786983,116.579398,107.851790,74.340386,135.922573,115.305683,134.742393,119.083231,111.434450,89.118650
2442,126.844547,102.736457,111.524733,75.405400,148.601986,132.389928,136.321958,119.875334,117.689978,107.434174,...,100.983003,118.492095,104.809426,62.674014,134.612206,110.296899,131.891479,119.752049,109.913072,85.073339

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 9.65
Fold 1 - Mean Absolute Error (MAE): 2.46
Fold 1 - Root Mean Squared Error (RMSE): 3.11
Fold 1 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 9.44
Fold 2 - Mean Absolute Error (MAE): 2.42
Fold 2 - Root Mean Squared Error (RMSE): 3.07
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.59
Fold 3 - Mean Absolute Error (MAE): 2.31
Fold 3 - Root Mean Squared Error (RMSE): 2.93
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 10.01
Fold 4 - Mean Absolute Error (MAE): 2.47
Fold 4 - Root Mean Squared Error (RMSE): 3.16
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 9.04
Fold 5 - Mean Absolute Error (MAE): 2.35
Fold 5 - Root Mean Squared Error (RMSE): 3.01
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 9.34
Mean - Mean Absolute Error (MAE): 2.40
Mean - Root Mean Squared Error (RMSE): 3.06
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 88.07
Fold 1 - Mean Absolute Error (MAE): 5.86
Fold 1 - Root Mean Squared Error (RMSE): 9.38
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 88.23
Fold 2 - Mean Absolute Error (MAE): 5.87
Fold 2 - Root Mean Squared Error (RMSE): 9.39
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 96.54
Fold 3 - Mean Absolute Error (MAE): 6.27
Fold 3 - Root Mean Squared Error (RMSE): 9.83
Fold 3 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 87.75
Fold 4 - Mean Absolute Error (MAE): 5.79
Fold 4 - Root Mean Squared Error (RMSE): 9.37
Fold 4 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 92.33
Fold 5 - Mean Absolute Error (MAE): 6.07
Fold 5 - Root Mean Squared Error (RMSE): 9.61
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 90.58
Mean - Mean Absolute Error (MAE): 5.97
Mean - Root Mean Squared Error (RMSE): 9.52
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 18.80
Fold 1 - Mean Absolute Error (MAE): 3.38
Fold 1 - Root Mean Squared Error (RMSE): 4.34
Fold 1 - Time taken: 2.57 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 19.37
Fold 2 - Mean Absolute Error (MAE): 3.42
Fold 2 - Root Mean Squared Error (RMSE): 4.40
Fold 2 - Time taken: 3.03 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 19.77
Fold 3 - Mean Absolute Error (MAE): 3.43
Fold 3 - Root Mean Squared Error (RMSE): 4.45
Fold 3 - Time taken: 4.05 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 20.69
Fold 4 - Mean Absolute Error (MAE): 3.49
Fold 4 - Root Mean Squared Error (RMSE): 4.55
Fold 4 - Time taken: 3.97 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 19.01
Fold 5 - Mean Absolute Error (MAE): 3.43
Fold 5 - Root Mean Squared Error (RMSE): 4.36
Fold 5 - Time taken: 3.93 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 19.53
Mean - Mean Absolute Error (MAE): 3.43
Mean - Root Mean Squared Error (RMSE): 4.42
Mean - Time taken: 3.51 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.43
Fold 1 - Mean Absolute Error (MAE): 1.49
Fold 1 - Root Mean Squared Error (RMSE): 2.33
Fold 1 - Time taken: 0.08 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.92
Fold 2 - Mean Absolute Error (MAE): 1.61
Fold 2 - Root Mean Squared Error (RMSE): 2.43
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.87
Fold 3 - Mean Absolute Error (MAE): 1.58
Fold 3 - Root Mean Squared Error (RMSE): 2.42
Fold 3 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 6.12
Fold 4 - Mean Absolute Error (MAE): 1.63
Fold 4 - Root Mean Squared Error (RMSE): 2.47
Fold 4 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 6.39
Fold 5 - Mean Absolute Error (MAE): 1.64
Fold 5 - Root Mean Squared Error (RMSE): 2.53
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.95
Mean - Mean Absolute Error (MAE): 1.59
Mean - Root Mean Squared Error (RMSE): 2.44
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 21.67
Fold 1 - Mean Absolute Error (MAE): 3.36
Fold 1 - Root Mean Squared Error (RMSE): 4.66
Fold 1 - Time taken: 2.02 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 20.67
Fold 2 - Mean Absolute Error (MAE): 3.28
Fold 2 - Root Mean Squared Error (RMSE): 4.55
Fold 2 - Time taken: 1.98 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 21.17
Fold 3 - Mean Absolute Error (MAE): 3.33
Fold 3 - Root Mean Squared Error (RMSE): 4.60
Fold 3 - Time taken: 2.00 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 22.34
Fold 4 - Mean Absolute Error (MAE): 3.47
Fold 4 - Root Mean Squared Error (RMSE): 4.73
Fold 4 - Time taken: 2.00 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 21.20
Fold 5 - Mean Absolute Error (MAE): 3.37
Fold 5 - Root Mean Squared Error (RMSE): 4.60
Fold 5 - Time taken: 2.11 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 21.41
Mean - Mean Absolute Error (MAE): 3.36
Mean - Root Mean Squared Error (RMSE): 4.63
Mean - Time taken: 2.02 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_scattered_48_reg_frontback_random.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_scattered_48_reg_frontback_random.xlsx file")

Results saved to Results__PL_scattered_48_reg_frontback_random.xlsx file