# Importing Libraries for Data Engineering

In [1]:
import numpy as np
import pandas as pd

# Loading Dataset

In [2]:
sensors_data = pd.read_excel('PL_scattered_48_frontback_200_iReg3.xlsx', header=None)

In [3]:
sensors_data

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,102.657686,132.906796,69.395579,116.247728,134.165270,144.300561,109.635434,137.199497,83.808157,106.047110,...,74.348295,93.414551,85.680223,85.732215,114.233062,117.551497,100.176779,137.511627,69.519193,111.338922
1,106.015458,133.374168,70.108728,114.984777,124.267877,143.017543,102.669444,131.631784,90.616822,101.569904,...,88.575817,83.666016,89.490504,84.080742,117.140600,116.115547,101.646443,130.928551,64.144658,118.911792
2,105.016479,131.948970,72.933229,113.704724,129.049498,147.601375,107.022879,130.429872,90.211846,114.103948,...,85.955132,95.262966,85.099049,85.761936,108.530922,115.655723,98.976566,138.621300,61.372041,114.440561
3,107.608962,132.028002,69.623523,114.127130,130.958510,144.114449,105.191578,133.827359,85.409511,100.567509,...,88.682847,82.042054,90.796971,86.523834,109.949991,111.511165,102.498073,133.603244,66.267803,109.845709
4,98.958183,134.829311,71.496807,114.602050,124.875126,140.243715,107.622896,136.522543,90.565813,112.920485,...,82.874522,85.974361,87.436142,85.458480,114.283434,118.656477,107.522905,135.406785,59.028964,114.620359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.805280,118.102836,98.448654,71.947618,160.639157,138.304240,131.038539,115.253142,100.150043,93.459011,...,82.640684,109.414148,93.505118,74.230570,122.963351,115.190337,131.905047,118.764000,103.885849,69.634893
2439,137.995616,104.040728,98.572998,74.694592,153.708255,143.190286,127.279128,110.243140,107.421572,96.800479,...,86.214730,115.263974,91.041455,72.795796,117.256276,109.912118,136.390686,122.547029,112.747847,82.091139
2440,133.975742,110.402924,107.383883,70.435353,157.890129,134.816162,132.624971,104.572070,103.713391,87.323995,...,88.629085,103.008754,84.705761,68.544436,121.068658,111.468523,136.043718,121.695350,110.547913,75.827787
2441,131.525842,109.865527,106.694592,77.993850,157.147537,136.308408,127.453086,114.634655,114.144282,95.157683,...,82.013371,109.355067,93.079703,69.416806,132.563103,111.977363,131.651187,118.311085,94.252735,79.993959
2442,128.821184,104.833698,99.435955,79.166458,159.806481,141.437226,135.131140,115.576767,104.755249,93.510192,...,82.899793,102.836156,92.512735,68.343798,124.937857,120.312100,131.169911,115.426646,106.536595,77.302488

In [4]:
position_data = pd.read_excel('real x-y-z positions of 2443 locations.xlsx', header=None)

In [5]:
position_data

              0          1      2
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

# Data Engineering

### Sensors Data -- Labeling Columns

In [6]:
Sensors_Number_of_Columns = sensors_data.shape[1]

In [7]:
Sensors_columns = ["sensor" + str(x) for x in range(1,Sensors_Number_of_Columns + 1)]
sensors_data.columns = (Sensors_columns)

In [8]:
sensors_data

,sensor1,sensor2,sensor3,sensor4,sensor5,sensor6,sensor7,sensor8,sensor9,sensor10,...,sensor39,sensor40,sensor41,sensor42,sensor43,sensor44,sensor45,sensor46,sensor47,sensor48
0,102.657686,132.906796,69.395579,116.247728,134.165270,144.300561,109.635434,137.199497,83.808157,106.047110,...,74.348295,93.414551,85.680223,85.732215,114.233062,117.551497,100.176779,137.511627,69.519193,111.338922
1,106.015458,133.374168,70.108728,114.984777,124.267877,143.017543,102.669444,131.631784,90.616822,101.569904,...,88.575817,83.666016,89.490504,84.080742,117.140600,116.115547,101.646443,130.928551,64.144658,118.911792
2,105.016479,131.948970,72.933229,113.704724,129.049498,147.601375,107.022879,130.429872,90.211846,114.103948,...,85.955132,95.262966,85.099049,85.761936,108.530922,115.655723,98.976566,138.621300,61.372041,114.440561
3,107.608962,132.028002,69.623523,114.127130,130.958510,144.114449,105.191578,133.827359,85.409511,100.567509,...,88.682847,82.042054,90.796971,86.523834,109.949991,111.511165,102.498073,133.603244,66.267803,109.845709
4,98.958183,134.829311,71.496807,114.602050,124.875126,140.243715,107.622896,136.522543,90.565813,112.920485,...,82.874522,85.974361,87.436142,85.458480,114.283434,118.656477,107.522905,135.406785,59.028964,114.620359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2438,132.805280,118.102836,98.448654,71.947618,160.639157,138.304240,131.038539,115.253142,100.150043,93.459011,...,82.640684,109.414148,93.505118,74.230570,122.963351,115.190337,131.905047,118.764000,103.885849,69.634893
2439,137.995616,104.040728,98.572998,74.694592,153.708255,143.190286,127.279128,110.243140,107.421572,96.800479,...,86.214730,115.263974,91.041455,72.795796,117.256276,109.912118,136.390686,122.547029,112.747847,82.091139
2440,133.975742,110.402924,107.383883,70.435353,157.890129,134.816162,132.624971,104.572070,103.713391,87.323995,...,88.629085,103.008754,84.705761,68.544436,121.068658,111.468523,136.043718,121.695350,110.547913,75.827787
2441,131.525842,109.865527,106.694592,77.993850,157.147537,136.308408,127.453086,114.634655,114.144282,95.157683,...,82.013371,109.355067,93.079703,69.416806,132.563103,111.977363,131.651187,118.311085,94.252735,79.993959
2442,128.821184,104.833698,99.435955,79.166458,159.806481,141.437226,135.131140,115.576767,104.755249,93.510192,...,82.899793,102.836156,92.512735,68.343798,124.937857,120.312100,131.169911,115.426646,106.536595,77.302488

### Converting to Pandas Dataframe

In [9]:
sensors_data = pd.DataFrame(sensors_data)

### Position Data -- Labeling Columns

In [10]:
position_data.columns = ['Pos X', 'Pos Y', 'Pos Z']

In [11]:
position_data

          Pos X      Pos Y  Pos Z
0    -45.581275  30.239368 -60.00
1    -45.188830  30.181623 -59.96
2    -44.791865  30.131806 -59.92
3    -44.390422  30.089935 -59.88
4    -43.984540  30.056029 -59.84
...         ...        ...    ...
2438 -59.939858  51.788725  37.52
2439 -59.963718  51.389997  37.56
2440 -59.981583  50.990713  37.60
2441 -59.993448  50.591032  37.64
2442 -59.999315  50.191116  37.68

[2443 rows x 3 columns]

### Converting to Pandas Dataframe

In [12]:
position_data = pd.DataFrame(position_data)

# Importing Libraries

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

import time
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Converting Numpy Arrays to Pandas DataFrames for Sensor and Position Data

In [14]:
X = sensors_data
y = position_data

# convert numpy array into pandas dataframe
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define models

In [15]:
models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), KNeighborsRegressor(), XGBRegressor()]

# Define k-fold cross-validation

In [16]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Create empty dictionary to store the results

In [17]:
results_dict = {
    "Model": [],
    "Fold": [],
    "Mean Squared Error (MSE)": [],
    "Mean Absolute Error (MAE)": [],
    "Root Mean Squared Error (RMSE)": [],
    "Time taken": []
}

# Train and evaluate each model using k-fold cross-validation

In [18]:
for model in models:
    # Evaluate the performance of the model using k-fold cross-validation
    scores_mse = []
    scores_mae = []
    scores_rmse = []
    times = []
    for i, (train_index, test_index) in enumerate(kfold.split(X)):
        start_time = time.time()
        
        X_train_fold, X_val_fold = X.iloc[train_index], X.iloc[test_index]
        y_train_fold, y_val_fold = y.iloc[train_index], y.iloc[test_index]
        model.fit(X_train_fold, y_train_fold)
        y_pred_fold = model.predict(X_val_fold)
        
        
        mse = mean_squared_error(y_val_fold, y_pred_fold)
        mae = mean_absolute_error(y_val_fold, y_pred_fold)
        rmse = np.sqrt(mse)
        end_time = time.time()
        time_taken = end_time - start_time
        scores_mse.append(mse)
        scores_mae.append(mae)
        scores_rmse.append(rmse)
        times.append(time_taken)
        
        # Add the results to the dictionary
        results_dict["Model"].append(type(model).__name__)
        results_dict["Fold"].append(i+1)
        results_dict["Mean Squared Error (MSE)"].append(mse)
        results_dict["Mean Absolute Error (MAE)"].append(mae)
        results_dict["Root Mean Squared Error (RMSE)"].append(rmse)
        results_dict["Time taken"].append(time_taken)
        
        print(f"Model: {type(model).__name__}")
        print(f"Fold {i+1} - Mean Squared Error (MSE): {mse:.2f}")
        print(f"Fold {i+1} - Mean Absolute Error (MAE): {mae:.2f}")
        print(f"Fold {i+1} - Root Mean Squared Error (RMSE): {rmse:.2f}")
        print(f"Fold {i+1} - Time taken: {time_taken:.2f} seconds")
    
    # Calculate mean time and results for all the folds
    mean_mse = np.mean(scores_mse)
    mean_mae = np.mean(scores_mae)
    mean_rmse = np.mean(scores_rmse)
    mean_time = np.mean(times)

    # Add the mean results to the dictionary
    results_dict["Model"].append(type(model).__name__)
    results_dict["Fold"].append("Mean")
    results_dict["Mean Squared Error (MSE)"].append(mean_mse)
    results_dict["Mean Absolute Error (MAE)"].append(mean_mae)
    results_dict["Root Mean Squared Error (RMSE)"].append(mean_rmse)
    results_dict["Time taken"].append(mean_time)

    print(f"Model: {type(model).__name__}")
    print(f"Mean - Mean Squared Error (MSE): {mean_mse:.2f}")
    print(f"Mean - Mean Absolute Error (MAE): {mean_mae:.2f}")
    print(f"Mean - Root Mean Squared Error (RMSE): {mean_rmse:.2f}")
    print(f"Mean - Time taken: {mean_time:.2f} seconds")

    
#Convert the results dictionary into a pandas dataframe
results_df = pd.DataFrame.from_dict(results_dict)

Model: LinearRegression
Fold 1 - Mean Squared Error (MSE): 8.94
Fold 1 - Mean Absolute Error (MAE): 2.42
Fold 1 - Root Mean Squared Error (RMSE): 2.99
Fold 1 - Time taken: 0.02 seconds
Model: LinearRegression
Fold 2 - Mean Squared Error (MSE): 8.36
Fold 2 - Mean Absolute Error (MAE): 2.30
Fold 2 - Root Mean Squared Error (RMSE): 2.89
Fold 2 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 3 - Mean Squared Error (MSE): 8.50
Fold 3 - Mean Absolute Error (MAE): 2.35
Fold 3 - Root Mean Squared Error (RMSE): 2.91
Fold 3 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 4 - Mean Squared Error (MSE): 8.66
Fold 4 - Mean Absolute Error (MAE): 2.35
Fold 4 - Root Mean Squared Error (RMSE): 2.94
Fold 4 - Time taken: 0.01 seconds
Model: LinearRegression
Fold 5 - Mean Squared Error (MSE): 8.66
Fold 5 - Mean Absolute Error (MAE): 2.35
Fold 5 - Root Mean Squared Error (RMSE): 2.94
Fold 5 - Time taken: 0.01 seconds
Model: LinearRegression
Mean - Mean Squared Error (MSE): 8.62
Mean - Mean Absolute Error (MAE): 2.36
Mean - Root Mean Squared Error (RMSE): 2.94
Mean - Time taken: 0.01 seconds
Model: DecisionTreeRegressor
Fold 1 - Mean Squared Error (MSE): 105.37
Fold 1 - Mean Absolute Error (MAE): 6.51
Fold 1 - Root Mean Squared Error (RMSE): 10.27
Fold 1 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 2 - Mean Squared Error (MSE): 84.79
Fold 2 - Mean Absolute Error (MAE): 5.68
Fold 2 - Root Mean Squared Error (RMSE): 9.21
Fold 2 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 3 - Mean Squared Error (MSE): 102.63
Fold 3 - Mean Absolute Error (MAE): 6.35
Fold 3 - Root Mean Squared Error (RMSE): 10.13
Fold 3 - Time taken: 0.04 seconds
Model: DecisionTreeRegressor
Fold 4 - Mean Squared Error (MSE): 92.86
Fold 4 - Mean Absolute Error (MAE): 6.04
Fold 4 - Root Mean Squared Error (RMSE): 9.64
Fold 4 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Fold 5 - Mean Squared Error (MSE): 88.34
Fold 5 - Mean Absolute Error (MAE): 6.04
Fold 5 - Root Mean Squared Error (RMSE): 9.40
Fold 5 - Time taken: 0.05 seconds
Model: DecisionTreeRegressor
Mean - Mean Squared Error (MSE): 94.80
Mean - Mean Absolute Error (MAE): 6.12
Mean - Root Mean Squared Error (RMSE): 9.73
Mean - Time taken: 0.05 seconds
Model: RandomForestRegressor
Fold 1 - Mean Squared Error (MSE): 16.27
Fold 1 - Mean Absolute Error (MAE): 3.23
Fold 1 - Root Mean Squared Error (RMSE): 4.03
Fold 1 - Time taken: 2.51 seconds
Model: RandomForestRegressor
Fold 2 - Mean Squared Error (MSE): 18.42
Fold 2 - Mean Absolute Error (MAE): 3.41
Fold 2 - Root Mean Squared Error (RMSE): 4.29
Fold 2 - Time taken: 2.59 seconds
Model: RandomForestRegressor
Fold 3 - Mean Squared Error (MSE): 20.94
Fold 3 - Mean Absolute Error (MAE): 3.53
Fold 3 - Root Mean Squared Error (RMSE): 4.58
Fold 3 - Time taken: 3.98 seconds
Model: RandomForestRegressor
Fold 4 - Mean Squared Error (MSE): 17.21
Fold 4 - Mean Absolute Error (MAE): 3.25
Fold 4 - Root Mean Squared Error (RMSE): 4.15
Fold 4 - Time taken: 4.16 seconds
Model: RandomForestRegressor
Fold 5 - Mean Squared Error (MSE): 18.51
Fold 5 - Mean Absolute Error (MAE): 3.38
Fold 5 - Root Mean Squared Error (RMSE): 4.30
Fold 5 - Time taken: 3.97 seconds
Model: RandomForestRegressor
Mean - Mean Squared Error (MSE): 18.27
Mean - Mean Absolute Error (MAE): 3.36
Mean - Root Mean Squared Error (RMSE): 4.27
Mean - Time taken: 3.44 seconds
Model: KNeighborsRegressor
Fold 1 - Mean Squared Error (MSE): 5.05
Fold 1 - Mean Absolute Error (MAE): 1.49
Fold 1 - Root Mean Squared Error (RMSE): 2.25
Fold 1 - Time taken: 0.09 seconds
Model: KNeighborsRegressor
Fold 2 - Mean Squared Error (MSE): 5.36
Fold 2 - Mean Absolute Error (MAE): 1.51
Fold 2 - Root Mean Squared Error (RMSE): 2.32
Fold 2 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Fold 3 - Mean Squared Error (MSE): 5.38
Fold 3 - Mean Absolute Error (MAE): 1.53
Fold 3 - Root Mean Squared Error (RMSE): 2.32
Fold 3 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 4 - Mean Squared Error (MSE): 4.89
Fold 4 - Mean Absolute Error (MAE): 1.43
Fold 4 - Root Mean Squared Error (RMSE): 2.21
Fold 4 - Time taken: 0.03 seconds
Model: KNeighborsRegressor
Fold 5 - Mean Squared Error (MSE): 5.14
Fold 5 - Mean Absolute Error (MAE): 1.48
Fold 5 - Root Mean Squared Error (RMSE): 2.27
Fold 5 - Time taken: 0.02 seconds
Model: KNeighborsRegressor
Mean - Mean Squared Error (MSE): 5.17
Mean - Mean Absolute Error (MAE): 1.49
Mean - Root Mean Squared Error (RMSE): 2.27
Mean - Time taken: 0.04 seconds
Model: XGBRegressor
Fold 1 - Mean Squared Error (MSE): 17.87
Fold 1 - Mean Absolute Error (MAE): 3.12
Fold 1 - Root Mean Squared Error (RMSE): 4.23
Fold 1 - Time taken: 1.98 seconds
Model: XGBRegressor
Fold 2 - Mean Squared Error (MSE): 19.16
Fold 2 - Mean Absolute Error (MAE): 3.22
Fold 2 - Root Mean Squared Error (RMSE): 4.38
Fold 2 - Time taken: 1.99 seconds
Model: XGBRegressor
Fold 3 - Mean Squared Error (MSE): 19.83
Fold 3 - Mean Absolute Error (MAE): 3.24
Fold 3 - Root Mean Squared Error (RMSE): 4.45
Fold 3 - Time taken: 1.93 seconds
Model: XGBRegressor
Fold 4 - Mean Squared Error (MSE): 17.08
Fold 4 - Mean Absolute Error (MAE): 3.05
Fold 4 - Root Mean Squared Error (RMSE): 4.13
Fold 4 - Time taken: 1.94 seconds
Model: XGBRegressor
Fold 5 - Mean Squared Error (MSE): 18.79
Fold 5 - Mean Absolute Error (MAE): 3.22
Fold 5 - Root Mean Squared Error (RMSE): 4.33
Fold 5 - Time taken: 1.96 seconds
Model: XGBRegressor
Mean - Mean Squared Error (MSE): 18.54
Mean - Mean Absolute Error (MAE): 3.17
Mean - Root Mean Squared Error (RMSE): 4.30
Mean - Time taken: 1.96 seconds

# Saving the results to an Excel file

In [19]:
results_df.to_excel("Results__PL_scattered_48_frontback_200_iReg3.xlsx", index=False)

#Print a message indicating that the results have been saved to a file
print("Results saved to Results__PL_scattered_48_frontback_200_iReg3.xlsx file")

Results saved to Results__PL_scattered_48_frontback_200_iReg3.xlsx file